export type IkazRengi = "kirmizi" | "sari" | "mavi" | "yesil" | "beyaz";
export type AciliyetDuzeyi = "hemen_dur" | "yakin_servis" | "dikkat" | "bilgi";
export type ModelUyumu = "t10x" | "t10f" | "hepsi";

export interface IkazSembolu {
  id: string;
  ad: string;
  renk: IkazRengi;
  aciliyet: AciliyetDuzeyi;
  model: ModelUyumu;
  sembol_tanimi: string; // Claude'a gönderilecek görsel açıklama
  gorsel?: string; // /ikaz/ klasöründeki PNG dosyası
  anlami: string;
  nedenler: string[];
  yapilacaklar: string[];
  servis_gerekli: boolean;
  not?: string;
  anahtar_kelimeler: string[];
}

// ─── Kırmızı İkazlar (Acil — Hemen Dur) ─────────────────────────────────────

const KIRMIZI_IKAZLAR: IkazSembolu[] = [
  {
    id: "batarya-kritik",
    ad: "Kritik Batarya Şarj Seviyesi",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    sembol_tanimi: "Kırmızı renkte, içinde ünlem işareti olan batarya simgesi veya çok düşük şarj göstergesi",
    anlami: "Batarya şarj seviyesi kritik eşiğin altına düştü. Araç yakında hareket edemez hale gelir.",
    nedenler: [
      "Şarj yapılmadan uzun süre kullanım",
      "Soğuk havada batarya kapasitesinin geçici düşüşü",
      "Batarya yönetim sistemi arızası",
    ],
    yapilacaklar: [
      "Güvenli bir yere çek ve hemen şarja bağla",
      "Togg Care'i ara: 0 850 222 86 44",
      "Trugo veya uyumlu şarj istasyonu bul",
      "Isıtma/soğutma sistemini kapat, menzil tasarrufu sağla",
    ],
    servis_gerekli: false,
    not: "Araç bataryası %0'a ulaşırsa flatbed çekici gerekebilir.",
    anahtar_kelimeler: ["batarya", "şarj yok", "menzil bitti", "kırmızı batarya", "düşük şarj"],
  },
  {
    id: "park-freni-ariza",
    ad: "Elektromekanik Park Freni Arızası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img17.png",
    sembol_tanimi: "Kırmızı renkte daire içinde P harfi — yanıp söner",
    anlami: "Elektromekanik park freni arızası.",
    nedenler: [
      "Park freni aktüatörü arızası",
      "Park freni sensör hatası",
      "Elektrik sistemi sorunu",
    ],
    yapilacaklar: [
      "Vitesi P konumuna al, düz zeminde park et",
      "Togg yetkili servisine git",
      "Eğimli zeminde araç bırakma",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["park freni arıza", "el freni arıza", "EPB arıza"],
  },
  {
    id: "hava-yastigi",
    ad: "Hava Yastığı Sistem Hatası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img12.png",
    sembol_tanimi: "Kırmızı renkte, önünde yuvarlak balon olan oturan insan silüeti",
    anlami: "Hava yastığı sistem hatası. Kaza anında hava yastıkları çalışmayabilir.",
    nedenler: [
      "SRS kontrol ünitesi arızası",
      "Hava yastığı sensör bağlantı sorunu",
      "Akü bağlantısı kesildikten sonra hata kodu oluşması",
      "Araç fiziksel hasar görmüş",
    ],
    yapilacaklar: [
      "Sürüşe devam edebilirsin ancak kaza riskini göz önünde bulundur",
      "En kısa sürede yetkili Togg servisine git",
      "Sistemi kendin sıfırlamaya ya da müdahale etmeye çalışma",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["hava yastığı", "airbag", "SRS", "emniyet kemeri"],
  },
  {
    id: "motor-ariza",
    ad: "Motor Sistemi Hatası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    sembol_tanimi: "Kırmızı renkte motor/araç gövdesi simgesi",
    anlami: "Motor sistemi hatası. Güç kaybı yaşanabilir.",
    nedenler: [
      "Tahrik motoru aşırı ısınması",
      "İnverter arızası",
      "Yüksek voltaj sistemi hatası",
      "Motor sargı hasarı",
    ],
    yapilacaklar: [
      "Güvenli bir yerde dur",
      "Aracı kapatıp 5 dakika bekle, yeniden başlatmayı dene",
      "Uyarı devam ederse Togg Care'i ara",
      "Aşırı sıcaklık söz konusuysa araçtan uzaklaş",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["motor", "tahrik", "arıza", "güç yok", "elektrik motoru"],
  },
  {
    id: "yuksek-voltaj",
    ad: "Yüksek Voltaj Sistemi Arızası",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page2_img21.png",
    sembol_tanimi: "Kırmızı renkte uyarı üçgeni içinde yıldırım işareti",
    anlami: "Yüksek voltaj sistemi arızası. Ciddi elektrik çarpması riski.",
    nedenler: [
      "Yüksek voltaj yalıtım arızası",
      "Batarya sızıntısı veya hasar",
      "Şarj sistemi kısa devre",
      "Kaza sonrası sistem güvenlik kilidinin devreye girmesi",
    ],
    yapilacaklar: [
      "Hemen dur, motoru kapat",
      "Araçtan uzaklaş — en az 10 metre",
      "Turuncu kabloları ve bileşenleri ASLA dokunma",
      "112 ve Togg Care'i ara",
    ],
    servis_gerekli: true,
    not: "Turuncu renkli kablo veya bileşenler 400V taşır. Dokunmayın.",
    anahtar_kelimeler: ["yüksek voltaj", "HV", "elektrik çarpması", "400V", "batarya hasar"],
  },
  {
    id: "guc-direksiyon",
    ad: "Elektrikli Direksiyon Hatası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img13.png",
    sembol_tanimi: "Kırmızı renkte direksiyon simidi içinde ünlem işareti",
    anlami: "Elektrikli direksiyon hatası. Direksiyonu döndürmek çok zorlaşabilir.",
    nedenler: [
      "EPS kontrol ünitesi arızası",
      "Direksiyon motor sensör hatası",
      "12V yardımcı akü zayıf veya boş",
      "Direksiyon mili mekanik sorunu",
    ],
    yapilacaklar: [
      "Güvenli hızda yavaşla, dikkatli sürdür",
      "Direksiyon ağırlaştığı için önceden dönüşleri planla",
      "Mümkün olan ilk fırsatta dur",
      "Yetkili servise çek",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["direksiyon", "EPS", "güç direksiyonu", "direksiyon ağır"],
  },
];

// ─── Sarı Uyarılar (Dikkat — Yakında Servis) ─────────────────────────────────

const SARI_UYARILAR: IkazSembolu[] = [
  {
    id: "lastik-basinc",
    ad: "Lastik Basınç Uyarısı (TPMS)",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img16.png",
    sembol_tanimi: "Sarı renkte, kesik çizgili zemin üzerinde duran ve içinde ünlem işareti olan lastik/tekerlek kesiti simgesi",
    anlami: "Bir veya birden fazla lastiğin basıncı önerilen değerin altında.",
    nedenler: [
      "Soğuk hava nedeniyle basınç düşüşü (normal)",
      "Yavaş lastik delinmesi",
      "Valf kapağı gevşemiş",
      "Lastik zararı",
    ],
    yapilacaklar: [
      "En yakın güvenli yerde dur, lastikleri görsel kontrol et",
      "Lastik basınç sensörünü (kapı kenarı etiketi) kontrol et: T10X ön 2.5 bar / arka 2.3 bar",
      "Uygun basınca şişir",
      "15 km/s üzerinde sürmeden önce basıncı düzelt",
    ],
    servis_gerekli: false,
    not: "Soğuk havada her 10°C düşüş için yaklaşık 0.1 bar basınç kaybı normaldir.",
    anahtar_kelimeler: ["lastik", "TPMS", "basınç", "patlak", "tekerlek"],
  },
  {
    id: "abs-ariza",
    ad: "ABS Sistemi Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page3_img16.png",
    sembol_tanimi: "Sarı renkte ABS yazısı, genellikle daire içinde",
    anlami: "Kilitlenme önleme fren sistemi devre dışı. Normal frenleme çalışır ama ani frende tekerlekler kilitlenebilir.",
    nedenler: [
      "ABS tekerlek hız sensörü arızası",
      "ABS kontrol ünitesi hatası",
      "Fren hidroliği baskı sensörü",
    ],
    yapilacaklar: [
      "Normal sürüşe devam edebilirsin",
      "Islak ve kaygan zeminde özellikle dikkatli ol",
      "Ani frenleme yaparsan tekerlekler kilitlenebilir — daha uzun mesafe bırak",
      "Yetkili serviste kontrol ettir",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["ABS", "kilitlenme", "fren", "kayma"],
  },
  {
    id: "esp-esc",
    ad: "Elektronik Denge Kontrolü Arızası / Devrede",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img10.png",
    sembol_tanimi: "Sarı renkte kayan araç silüeti — sabit yanıyorsa arıza, yanıp sönüyorsa devreye girdi",
    anlami: "Denge kontrol sistemi müdahalede bulunuyor VEYA sistem devre dışı bırakıldı.",
    nedenler: [
      "Kaygan zeminde ESP devreye girdi (normal yanıp sönme)",
      "Sürücü tarafından devre dışı bırakıldı",
      "Sistem arızası (sabit yanarsa)",
    ],
    yapilacaklar: [
      "Sürekli yanıp sönüyorsa: kaygan zeminde, hızı düşür, düzgün sürdür",
      "Sabit yanıyorsa: sistem kapalı — ıslak zeminde dikkat",
      "Servis uyarısıyla birlikte yanıyorsa: yetkili servise git",
    ],
    servis_gerekli: false,
    not: "ESP lambası yanıp sönüyorsa sistem çalışıyor demektir — bu normal.",
    anahtar_kelimeler: ["ESP", "ESC", "denge", "kayma", "kayan araba"],
  },
  {
    id: "sarj-sistemi",
    ad: "Şarj Sistemi Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img14.png",
    sembol_tanimi: "Sarı renkte şarj fişi/konnektör simgesi veya yıldırım işareti ile birlikte ünlem",
    anlami: "AC veya DC şarj sisteminde sorun var. Araç şarj olmayabilir.",
    nedenler: [
      "Şarj kablosu düzgün takılmamış",
      "OBC (şarj ünitesi) arızası",
      "Şarj soketi hasarlı",
      "Yazılım hatası",
    ],
    yapilacaklar: [
      "Kabloyu çıkar ve yeniden tak",
      "Farklı şarj istasyonu dene",
      "Aracı yeniden başlat",
      "Sorun devam ederse Togg Care'i ara",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["şarj", "şarj yok", "şarj olmaz", "kablo", "şarj sistemi"],
  },
  {
    id: "batarya-dusuk",
    ad: "Yüksek Voltajlı Batarya Şarjı Düşük",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    sembol_tanimi: "Sarı/turuncu renkte şarj fişi ve düşük batarya simgesi kombinasyonu",
    anlami: "Yüksek voltajlı batarya şarjı düşük. Yakında şarj gerekiyor.",
    nedenler: ["Uzun sürüş", "Soğuk hava kapasitesi etkisi"],
    yapilacaklar: [
      "Yakın şarj istasyonu bul (Togg Harita veya Trugo uygulaması)",
      "Gereksiz elektrikli ekipmanları kapat",
      "Yüksek hız ve ani hızlanmadan kaçın",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["batarya düşük", "az şarj", "sarı batarya", "menzil az"],
  },
  {
    id: "yikama-sivisi",
    ad: "Yıkama Sıvısı Seviyesi Düşük",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img3.png",
    sembol_tanimi: "Sarı renkte, yelpaze şeklinde sprey çıkan ön cam ve su damlaları simgesi",
    anlami: "Silecek suyu deposu boşalmak üzere.",
    nedenler: ["Depo uzun süredir doldurulmamış"],
    yapilacaklar: [
      "En yakın benzin istasyonu veya market'ten silecek suyu al",
      "Kışın donmayan silecek sıvısı kullan (-20°C)",
      "Depoyu doldur — T10X ön kaporta sol tarafta",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["silecek suyu", "cam suyu", "wiper", "cam yıkama"],
  },
  {
    id: "batarya-sicaklik",
    ad: "Termal Sistem Soğutucu Sıvı Düşük",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    sembol_tanimi: "Sarı/turuncu renkte soğutucu/termal sistem simgesi, içinde sıvı seviyesi göstergesi",
    anlami: "Termal sistem soğutucu sıvı seviyesi düşük.",
    nedenler: [
      "Çok soğuk hava (batarya ön ısıtması gerekli)",
      "Uzun ve yüksek hızda sürüş sonrası aşırı ısınma",
      "Hızlı DC şarj sonrası sıcaklık yükselmesi",
    ],
    yapilacaklar: [
      "Soğuk havasada: 10-15 dakika bekle, batarya ısınır",
      "Sıcak havasada: gölge alanda park et, şarjı bekle",
      "Şarj hızı kısıtlandıysa normaldir — batarya korunuyor",
    ],
    servis_gerekli: false,
    not: "Batarya termal yönetim sistemi otomatik olarak devreye girer.",
    anahtar_kelimeler: ["batarya sıcak", "batarya soğuk", "ısınma", "sıcaklık", "thermal"],
  },
  {
    id: "park-freni",
    ad: "Elektromekanik Park Freni Etkin",
    renk: "kirmizi",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img18.png",
    sembol_tanimi: "Kırmızı/sarı renkte daire içinde P harfi — sabit yanıyorsa park freni etkin veya EBD uyarısı, yanıp sönüyorsa arıza",
    anlami: "Elektromekanik park freni etkin veya Elektronik fren kuvveti dağılımı uyarısı.",
    nedenler: [
      "Sürücü park freni açmayı unuttu",
      "Otomatik park freni aktif",
    ],
    yapilacaklar: [
      "Park freni butonuna bas ve serbest bırak",
      "Vites P konumuna al, freni bırak",
      "Uyarı kaybolmazsa Togg servisine git",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["park freni", "el freni", "P freni", "kırmızı P"],
  },
  {
    id: "motor-bakim",
    ad: "Motor Sistemi Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page2_img18.png",
    sembol_tanimi: "Sarı/turuncu renkte motor/araç gövdesi simgesi",
    anlami: "Motor sistemi uyarısı. Performans kısıtlaması olabilir.",
    nedenler: [
      "Çeşitli elektronik sistem hataları",
      "Sensör arızaları",
      "Yazılım hatası",
    ],
    yapilacaklar: [
      "Aracı kapatıp yeniden başlat",
      "Uyarı devam ederse yetkili servise git",
      "Togg Care ile iletişime geç — hata kodunu uzaktan okuyabilirler",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["servis", "arıza", "hata", "check", "genel uyarı"],
  },
];

// ─── Mavi / Yeşil Bilgi Lambaları ────────────────────────────────────────────

const BILGI_LAMBALARI: IkazSembolu[] = [
  {
    id: "sarj-aktif",
    ad: "Şarj Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page1_img19.png",
    sembol_tanimi: "Yeşil renkte şarj fişi simgesi veya yıldırım işareti — kablo bağlı görseli",
    anlami: "Araç başarıyla şarja bağlandı ve şarj oluyor.",
    nedenler: ["Şarj kablosu bağlı"],
    yapilacaklar: ["Şarj tamamlanana kadar bekle", "Trumore veya Togg uygulamasıyla şarj ilerlemesini takip et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["şarj oluyor", "şarj aktif", "yeşil şarj"],
  },
  {
    id: "uzun-far",
    ad: "Uzun Far Aktif",
    renk: "mavi",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img23.png",
    sembol_tanimi: "Mavi renkte, yatay çizgilerle sola doğru yayılan far ışığı simgesi",
    anlami: "Uzun (yüksek) huzmeli farlar aktif.",
    nedenler: ["Sürücü uzun far devreye aldı veya otomatik far sistemi açtı"],
    yapilacaklar: [
      "Karşıdan araç geliyorsa uzun farı kapat",
      "Otomatik far açıksa: sistem karşıdan araç tespit ettiğinde kısa fara geçer",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["uzun far", "yüksek huzme", "far", "mavi far"],
  },
  {
    id: "serit-takip",
    ad: "Şerit Takip Asistanı Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img4.png",
    sembol_tanimi: "Yeşil renkte, iki şerit çizgisi arasında ortalanmış araç simgesi",
    anlami: "Şerit takip asistanı aktif ve yol işaretlerini takip ediyor.",
    nedenler: ["ADAS sürücü destek sistemi açık"],
    yapilacaklar: ["Normal sürüşe devam et", "Direksiyon üzerinde ellerini tut"],
    servis_gerekli: false,
    anahtar_kelimeler: ["şerit", "lane assist", "şerit takip", "ADAS"],
  },
  {
    id: "adaptif-hiz",
    ad: "Adaptif Hız Sabitleyici Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page2_img8.png",
    sembol_tanimi: "Yeşil renkte hız göstergesi kadranı ve ok simgesi veya ACC yazısı",
    anlami: "Adaptif cruise control aktif. Araç önündeki araçla mesafeyi koruyarak hız ayarlıyor.",
    nedenler: ["Sürücü ACC sistemi devreye aldı"],
    yapilacaklar: [
      "Frene basınca veya direksiyonu yoğun çevirince devre dışı kalır",
      "Ayarlı hızı ve mesafeyi kontrol et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["cruise control", "ACC", "hız sabitleyici", "adaptif hız"],
  },
  {
    id: "ota-guncelleme",
    ad: "TruOS Yazılım Güncellemesi Mevcut",
    renk: "mavi",
    aciliyet: "bilgi",
    model: "hepsi",
    sembol_tanimi: "Mavi renkte daire yükleme oku veya bulut indirme simgesi — UPDATE veya OTA yazısı",
    anlami: "Araç için yeni bir yazılım güncellemesi hazır. İndirildi veya indiriliyor.",
    nedenler: ["Togg yeni TruOS sürümü yayınladı"],
    yapilacaklar: [
      "Aracı şarja bağla (%20 üzeri şarj gerekli)",
      "Wi-Fi'ye bağlan (veya hücresel ağ)",
      "Araç park halinde olmalı",
      "Güncelleme 30-60 dk sürebilir",
    ],
    servis_gerekli: false,
    not: "Güncelleme sırasında aracı kapatma veya kullanma.",
    anahtar_kelimeler: ["güncelleme", "OTA", "TruOS", "yazılım"],
  },
];

// ─── T10F'ye Özgü Semboller ───────────────────────────────────────────────────

const T10F_OZGUL: IkazSembolu[] = [
  {
    id: "yaya-koruma",
    ad: "Aktif Yaya Koruma Sistemi Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "t10f",
    sembol_tanimi: "Sarı renkte yürüyen insan silüeti ve kalkan/koruma simgesi",
    anlami: "T10F'ye özgü aktif yaya koruma sistemi (kaput yükseltme) arızalı.",
    nedenler: [
      "Kaput aktüatörü arızası",
      "Yaya algılama sensörü hatası",
    ],
    yapilacaklar: [
      "Yetkili Togg servisine git",
      "Sistemin devre dışı kalması kaza anında yaya korumasını azaltır",
    ],
    servis_gerekli: true,
    not: "Bu sistem yalnızca T10F'de bulunur, T10X'te yoktur.",
    anahtar_kelimeler: ["yaya koruma", "kaput", "aktif güvenlik", "T10F"],
  },
  {
    id: "awd-sistem",
    ad: "AWD / 4More Sistem Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "t10f",
    sembol_tanimi: "Sarı renkte dört tekerlekli araç üstten görünüm veya 4WD / AWD yazısı",
    anlami: "İki motorlu AWD sisteminde hata. Tek motora düşürülmüş olabilir.",
    nedenler: [
      "Arka motor kontrol ünitesi arızası",
      "AWD tork dağıtım sistemi hatası",
      "Yüksek sıcaklık nedeniyle geçici kısıtlama",
    ],
    yapilacaklar: [
      "Aracı kapatıp 10 dakika bekle — termal ise kendiliğinden geçer",
      "Devam ederse yetkili servise git",
    ],
    servis_gerekli: true,
    not: "T10F AWD versiyonuna özgü semboldür.",
    anahtar_kelimeler: ["AWD", "4More", "4x4", "çift motor", "T10F AWD"],
  },
];

// ─── Ek Kırmızı Kritik İkazlar ───────────────────────────────────────────────

const ILAVE_KIRMIZI_IKAZLAR: IkazSembolu[] = [
  {
    id: "emniyet-kemeri",
    ad: "Emniyet Kemeri Takılı Değil veya Hata",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page1_img7.png",
    sembol_tanimi: "Kırmızı renkte oturan insan silüeti, göğüs hizasında çapraz emniyet kemeri çizgisi — sabit veya yanıp söner",
    anlami: "Emniyet kemeri takılı değil veya hata. Sabit yanıyorsa hata, yanıp sönüyorsa kemer takılmamış.",
    nedenler: [
      "Emniyet kemeri takılmamış",
      "Emniyet kemeri tokası arızalı",
      "Emniyet kemeri sensörü hatası",
    ],
    yapilacaklar: [
      "Emniyet kemerini tak",
      "Yolcunun da kemerini taktığından emin ol",
      "Sorun devam ederse servise git",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["emniyet kemeri", "kemer", "seatbelt"],
  },
  {
    id: "aku-hata",
    ad: "Düşük Voltajlı Akü Hatası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img6.png",
    sembol_tanimi: "Kırmızı renkte dikdörtgen akü gövdesi, üstünde artı (+) ve eksi (-) terminaller",
    anlami: "Düşük voltajlı akü hatası. 12V yardımcı akü arızalı, elektronik sistemler etkilenebilir.",
    nedenler: [
      "Akü ömrü dolmuş",
      "Alternatör/şarj sistemi arızası",
      "Akü bağlantıları gevşemiş",
    ],
    yapilacaklar: [
      "Aracı güvenli yerde park et",
      "Togg Care'i ara: 0 850 222 86 44",
      "Yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["akü", "batarya", "12V", "akü hatası"],
  },
  {
    id: "termal-hata",
    ad: "Termal Sistem Hatası",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page2_img22.png",
    sembol_tanimi: "Kırmızı renkte motor/ısı değiştirgeci bloğu simgesi ile ısı dalgaları",
    anlami: "Batarya veya motor soğutma sistemi kritik arızada. Aşırı ısınma riski var.",
    nedenler: [
      "Soğutucu sıvı seviyesi kritik düşük",
      "Termal yönetim sistemi arızası",
      "Soğutma pompası hatası",
    ],
    yapilacaklar: [
      "Hemen güvenli yerde dur",
      "Motoru kapat",
      "Soğuyana kadar bekle",
      "Togg Care'i ara",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["termal", "ısınma", "soğutma", "thermal"],
  },
  {
    id: "hv-yangin",
    ad: "Yüksek Voltajlı Batarya Yangın Uyarısı",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    sembol_tanimi: "Kırmızı renkte uyarı üçgeni, batarya yangın mesajı ekranda görünür",
    anlami: "Sistem bataryada yangın tespit etti. DERHAL araçtan uzaklaş.",
    nedenler: [
      "Batarya termal kaçak (thermal runaway)",
      "Fiziksel hasar",
      "Şarj sistemi arızası",
    ],
    yapilacaklar: [
      "HEMEN dur ve aracı terk et — en az 50 metre uzaklaş",
      "112 ara",
      "Yakınına geçme",
      "Togg Care: 0 850 222 86 44",
    ],
    servis_gerekli: true,
    not: "Bu uyarı ekranda metin mesajı olarak da görünür. Araçtan derhal uzaklaş, kesinlikle geri dönme.",
    anahtar_kelimeler: ["yangın", "batarya yangın", "thermal runaway", "fire"],
  },
  {
    id: "ecall-ariza",
    ad: "eCall Acil Çağrı Sistemi Arızası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page4_img7.png",
    sembol_tanimi: "Kırmızı renkte SOS yazısı, bağlantı/telefon simgesiyle birlikte",
    anlami: "Araç içi acil çağrı sistemi (eCall) arızalı. Kaza anında otomatik acil çağrı yapılamaz.",
    nedenler: [
      "eCall modül arızası",
      "SIM kart sorunu",
      "Anten bağlantı hatası",
    ],
    yapilacaklar: [
      "Yetkili Togg servisine git",
      "Acil durumda telefonunuzla 112'yi arayın",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["eCall", "acil çağrı", "SOS", "112"],
  },
  {
    id: "fren-servo",
    ad: "Fren Servosu Servis Uyarısı",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    sembol_tanimi: "Kırmızı renkte daire içinde ünlem işareti — akıllı fren servosu veya rejeneratif fren kontrol uyarısı",
    anlami: "Akıllı fren servosu veya rejeneratif fren sistemi servis gerektiriyor.",
    nedenler: [
      "Fren servo arızası",
      "Rejeneratif fren sistemi hatası",
      "Fren kontrol ünitesi sorunu",
    ],
    yapilacaklar: [
      "Frenleme mesafeni artır",
      "Hız düşür",
      "Yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["fren servo", "rejeneratif fren", "fren kontrol"],
  },
];

// ─── Ek Sarı Uyarılar ────────────────────────────────────────────────────────

const ILAVE_SARI_UYARILAR: IkazSembolu[] = [
  {
    id: "fren-sivisi",
    ad: "Fren Sıvısı Seviyesi Düşük",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img9.png",
    sembol_tanimi: "Sarı renkte daire içinde ünlem — fren hidroliği uyarısı",
    anlami: "Fren hidrolik sıvısı seviyesi düşük. Frenleme performansı etkilenebilir.",
    nedenler: [
      "Fren sıvısı kaçağı",
      "Fren balatası aşıması nedeniyle seviye düşüşü",
      "Servis zamanı geldi",
    ],
    yapilacaklar: [
      "Hızı düşür, güvenli yerde dur",
      "Fren sıvısı seviyesini kontrol et (kaputu açma)",
      "Togg servisi çağır",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["fren sıvısı", "hidrolik", "brake fluid"],
  },
  {
    id: "yolcu-hava-yastigi",
    ad: "Ön Yolcu Hava Yastığı Devre Dışı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img5.png",
    sembol_tanimi: "Sarı renkte oturan yolcu figürü, üzerinde çarpı işareti veya 2 rakamı",
    anlami: "Ön yolcu koltuğu hava yastığı devre dışı bırakılmış veya arızalı.",
    nedenler: [
      "Çocuk koltuğu algılama sistemi devrede bırakıldı",
      "Yolcu koltuğu boş/sensör hatası",
      "Manuel devre dışı bırakma",
    ],
    yapilacaklar: [
      "Ön koltuğa çocuk koltuğu takılıysa bu normaldir",
      "Aksi halde yetkili servise git",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["yolcu hava yastığı", "airbag kapalı", "ön yolcu"],
  },
  {
    id: "aku-zayif",
    ad: "Düşük Voltajlı Akü Şarj Durumu Zayıf",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    sembol_tanimi: "Sarı renkte dikdörtgen akü gövdesi, artı ve eksi terminaller, düşük şarj göstergesi",
    anlami: "12V yardımcı akü şarj seviyesi zayıf. Elektronik sistemlerde gecikmeli tepki olabilir.",
    nedenler: [
      "Uzun süre park halinde kullanım",
      "Akü yaşlanması",
      "Şarj sistemi verimsizliği",
    ],
    yapilacaklar: [
      "En kısa sürede kısa bir sürüş yap veya aracı şarja bağla",
      "Sorun tekrarlarsa servise git",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["akü zayıf", "12V zayıf", "yardımcı akü"],
  },
  {
    id: "isik-ariza",
    ad: "Işık Arızası",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img8.png",
    sembol_tanimi: "Sarı renkte far veya ampul simgesi, etrafında ışık ışınları ve uyarı göstergesi",
    anlami: "Araç aydınlatma sisteminde bir veya birden fazla ampul arızası.",
    nedenler: [
      "Far ampulü yanmış",
      "Stop veya sinyal lambası arızası",
      "LED far modülü hatası",
    ],
    yapilacaklar: [
      "Hangi lambanın arızalı olduğunu kontrol et",
      "Ampulü değiştir veya servise git",
      "Gece sürüşlerinde dikkat et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["ışık arızası", "ampul", "far arızası", "lamba"],
  },
  {
    id: "fren-balata",
    ad: "Fren Balatası Değiştir",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img25.png",
    sembol_tanimi: "Sarı renkte fren diski ve yıpranmış balata göstergesi olan simge",
    anlami: "Fren balataları aşınma sınırına ulaştı. En kısa sürede değiştirilmeli.",
    nedenler: [
      "Balata ömrü doldu",
      "Aşınma sensörü tetiklendi",
    ],
    yapilacaklar: [
      "Yetkili Togg servisine git",
      "Erteleme — fren performansı düşük",
      "Frenleme mesafeni artır",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["fren balatası", "balata", "fren yıpranma"],
  },
  {
    id: "aeb-fcw",
    ad: "Gelişmiş Acil Frenleme / Ön Çarpışma Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    sembol_tanimi: "Sarı renkte önde araç ve çarpışma çizgileri — yanıp sönüyorsa uyarı, sabit yanıyorsa AEB devre dışı veya LIM PERF sınırlı performans",
    anlami: "Gelişmiş acil frenleme uyarısı veya çarpışma engelleyici devre dışı. Yanıp sönüyorsa ön çarpışma uyarısı.",
    nedenler: [
      "Önde araç/engel tespit edildi",
      "Sensör kirli veya engellenmiş",
      "Sistem manuel kapatılmış",
    ],
    yapilacaklar: [
      "Fren sistemini kontrol et",
      "Sensör ön camını temizle",
      "Güvenli mesafe bırak",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["AEB", "çarpışma önleme", "acil frenleme", "FCW"],
  },
  {
    id: "hv-batarya-dusuk",
    ad: "Yüksek Voltajlı Batarya Şarjı Düşük",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    sembol_tanimi: "Sarı renkte, içinde yıldırım/şimşek işareti olan batarya simgesi",
    anlami: "Ana traksiyon bataryası şarj seviyesi düşük. Araç yakında hız kısıtlaması uygulayabilir.",
    nedenler: [
      "Batarya şarj seviyesi %10-%20 arasına düştü",
      "Soğuk hava kapasitesi etkisi",
    ],
    yapilacaklar: [
      "Yakın şarj istasyonu bul",
      "Hızı düşür",
      "Performans kısıtlı olacak",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["yüksek voltaj batarya", "HV batarya düşük", "traksiyon bataryası"],
  },
  {
    id: "motor-sinirli",
    ad: "Sınırlı Motor Performansı Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img11.png",
    sembol_tanimi: "Sarı veya kırmızı renkte araç yan görünüm silüeti, güç/performans kısıtlama göstergesi",
    anlami: "Motor sistemi kısıtlı modda çalışıyor. Maksimum güç ve hız düşürülmüştür.",
    nedenler: [
      "Batarya veya motor aşırı ısınması",
      "HV sistem koruma modu",
      "Yazılım güvenlik kısıtlaması",
    ],
    yapilacaklar: [
      "Hızı azalt, klimayı kapat",
      "15-20 dakika soğuması için bekle",
      "Uyarı devam ederse Togg Care ara",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["sınırlı performans", "motor kısıtlı", "limp mode", "kaplumbağa modu"],
  },
  {
    id: "termal-sivisi",
    ad: "Termal Sistem Soğutucu Sıvı Düşük",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page2_img23.png",
    sembol_tanimi: "Sarı renkte motor/termal ünite simgesi, soğutucu sıvı seviye göstergesi veya termometre",
    anlami: "Batarya/motor soğutma sistemi sıvı seviyesi düşük.",
    nedenler: [
      "Soğutucu sıvı kaçağı",
      "Buharlaşma",
      "Servis zamanı",
    ],
    yapilacaklar: [
      "Kaputu açma (basınç altında olabilir)",
      "Togg servisine git",
      "Soğutucu sıvıyı kendin ekleme",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["termal sıvı", "soğutucu", "coolant"],
  },
  {
    id: "kor-nokta",
    ad: "Kör Nokta Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img4.png",
    sembol_tanimi: "Sarı renkte araç yan görünümü, radar dalgaları veya nesne uyarı simgesiyle birlikte",
    anlami: "Kör nokta izleme sistemi yan şeritte araç tespit etti. Dikkatli şerit değiştir.",
    nedenler: [
      "Yan şeritte araç var",
      "Kör nokta sensörü uyarısı",
    ],
    yapilacaklar: [
      "Ayna ve direkt bakışla kontrol et",
      "Acele şerit değiştirme",
      "Sinyal ver",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["kör nokta", "blind spot", "şerit değiştirme", "yan uyarı"],
  },
  {
    id: "buz-yol",
    ad: "Buzlu Yol Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page3_img15.png",
    sembol_tanimi: "Beyaz/sarı renkte kar tanesi veya buz kristali simgesi, yol/araç göstergesiyle",
    anlami: "Dış sıcaklık 4°C'nin altında, yol yüzeyi buzlanma riski taşıyor.",
    nedenler: [
      "Hava sıcaklığı 4°C altına düştü",
      "Yol buzlanma riski",
    ],
    yapilacaklar: [
      "Hızı düşür",
      "Frenleme mesafesini artır",
      "Ani fren ve direksiyon hareketlerinden kaçın",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["buz", "kar", "kaygan yol", "buzlu", "ice road"],
  },
  {
    id: "oto-durdurma-ariza",
    ad: "Auto Hold Arızası",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    sembol_tanimi: "Sarı/kırmızı renkte AUTO HOLD yazısı koyu arka planda",
    anlami: "Otomatik durdurma (Auto Hold) sistemi arızalı.",
    nedenler: [
      "Elektronik park freni hatası",
      "Fren sistemi elektronik arızası",
    ],
    yapilacaklar: [
      "Manuel park freni kullan",
      "Rampalarda ekstra dikkat",
      "Yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["auto hold", "otomatik durdurma", "AUTO HOLD arıza"],
  },
  {
    id: "uyku-tespit",
    ad: "Uyku Durumu Tespiti Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page4_img6.png",
    sembol_tanimi: "Sarı renkte göz simgesi, uyuklama tespit göstergesi",
    anlami: "Sürücü yorgunluk/uyku belirtisi gösteriyor. Mola tavsiye edilir.",
    nedenler: [
      "Uzun süre sürüş",
      "Yorgun sürücü davranışı tespit edildi",
    ],
    yapilacaklar: [
      "En yakın güvenli yerde dur ve mola ver",
      "En az 20 dakika dinlen",
      "Çay/kahve iç",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["uyku", "yorgunluk", "drowsiness", "mola"],
  },
];

// ─── Ek Bilgi Lambaları ───────────────────────────────────────────────────────

const ILAVE_BILGI_LAMBALARI: IkazSembolu[] = [
  {
    id: "sarj-kablosu",
    ad: "Şarj Kablosu Takılı",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page1_img19.png",
    sembol_tanimi: "Yeşil renkte şarj kablosu/konnektör fişi simgesi",
    anlami: "Şarj kablosu araca takılı. Araç şarj modunda ya da araç kilitli değilken kablo takılı.",
    nedenler: [
      "Şarj kablosu bağlı",
      "Şarj tamamlandı ve kablo hâlâ takılı",
    ],
    yapilacaklar: [
      "Şarj tamamlanınca kabloyu çıkar",
      "Park yerine göre kabloyu güvenli bırakabilirsin",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["şarj kablosu", "kablo takılı", "charge cable"],
  },
  {
    id: "suruse-hazir",
    ad: "Sürüşe Hazır (HAZIR)",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img19.png",
    sembol_tanimi: "Yeşil renkte HAZIR yazısı koyu arka planda",
    anlami: "Araç sürüşe hazır durumda. Motor sistemi aktif, sürüş mümkün.",
    nedenler: ["Araç çalıştırıldı ve hazır"],
    yapilacaklar: ["Normal sürüşe devam edebilirsin"],
    servis_gerekli: false,
    anahtar_kelimeler: ["HAZIR", "sürüşe hazır", "ready"],
  },
  {
    id: "kisa-far",
    ad: "Kısa Far Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img2.png",
    sembol_tanimi: "Yeşil/mavi renkte, yatay çizgilerle sola doğru yayılan ve alt kısımda kesik çizgili far ışığı simgesi (kısa huzme)",
    anlami: "Düşük huzmeli (kısa) farlar aktif.",
    nedenler: ["Far sistemi açık, kısa far seçili"],
    yapilacaklar: [
      "Normal sürüşe devam et",
      "Karanlıkta ve tünelde farlar açık olmalı",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["kısa far", "dipped headlights", "düşük huzme"],
  },
  {
    id: "yokus-inis",
    ad: "Yokuş İniş Kontrolü Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    sembol_tanimi: "Yeşil renkte eğimli zeminde inen araç simgesi, yokuş iniş sembolü",
    anlami: "Yokuş iniş kontrolü (HDC) aktif. Araç inişte sabit düşük hız korur.",
    nedenler: [
      "Sürücü HDC sistemi etkinleştirdi",
      "Dik iniş algılandı",
    ],
    yapilacaklar: [
      "Normal sürüşe devam et",
      "Fren gerekmeden araç hızını kontrol eder",
      "Çıkmak için butona bas",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["yokuş iniş", "HDC", "eğim kontrolü", "iniş kontrol"],
  },
  {
    id: "hiz-sabitleyici",
    ad: "Hız Sabitleyici Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page2_img10.png",
    sembol_tanimi: "Yeşil renkte hız kadranı/göstergesi simgesi, cruise control aktif göstergesi",
    anlami: "Standart hız sabitleyici (cruise control) aktif.",
    nedenler: ["Sürücü cruise control devreye aldı"],
    yapilacaklar: [
      "Fren veya gaz ile devre dışı kalır",
      "Etkin hızı kontrol et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["cruise control", "hız sabitleyici", "CC aktif"],
  },
  {
    id: "oto-durdurma",
    ad: "Auto Hold Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    sembol_tanimi: "Yeşil renkte AUTO HOLD yazısı koyu arka planda",
    anlami: "Otomatik durdurma (Auto Hold) aktif. Araç durakta veya kırmızı ışıkta otomatik tutulur.",
    nedenler: ["Auto Hold sistemi sürücü tarafından etkinleştirildi"],
    yapilacaklar: [
      "Gaz pedalına basınca araç hareket eder",
      "Normal sürüşe devam et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["auto hold", "otomatik durdurma aktif"],
  },
  {
    id: "sag-sinyal",
    ad: "Sağ Sinyal Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img17.png",
    sembol_tanimi: "Yeşil renkte sağa dönen ok işareti",
    anlami: "Sağ sinyal lambası çalışıyor.",
    nedenler: ["Sürücü sağ sinyal verdi"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["sağ sinyal", "sinyalizasyon", "dönüş lambası"],
  },
  {
    id: "sol-sinyal",
    ad: "Sol Sinyal Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img18.png",
    sembol_tanimi: "Yeşil renkte sola dönen ok işareti",
    anlami: "Sol sinyal lambası çalışıyor.",
    nedenler: ["Sürücü sol sinyal verdi"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["sol sinyal", "sinyalizasyon", "dönüş lambası"],
  },
  {
    id: "uzun-far-asistan",
    ad: "Uzun Far Asistanı Aktif",
    renk: "mavi",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img22.png",
    sembol_tanimi: "Mavi renkte, yatay çizgilerle sola doğru yayılan far ışığı ve daire içinde A harfi",
    anlami: "Otomatik uzun far sistemi aktif. Karşıdan araç gelince otomatik kısa fara geçer.",
    nedenler: ["Otomatik far sistemi açık"],
    yapilacaklar: [
      "Normal sürüşe devam et",
      "Sistem karşı araç gelince otomatik kısar",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["uzun far asistanı", "otomatik far", "auto high beam"],
  },
  {
    id: "sis-far",
    ad: "Sis Farı Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img10.png",
    sembol_tanimi: "Yeşil veya sarı renkte, eğimli çizgilerle yayılan far simgesi ve üç yatay dalga çizgisi (sis)",
    anlami: "Ön veya arka sis farı aktif.",
    nedenler: ["Sürücü sis farını açtı"],
    yapilacaklar: [
      "Sis yokken sis farını kapat (gözleri kamaştırabilir)",
      "Sis geçince normal fara dön",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["sis farı", "fog light", "sis lambası"],
  },
  {
    id: "park-lambasi",
    ad: "Park Lambası / Konum Lambası Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img9.png",
    sembol_tanimi: "Yeşil renkte iki köşe ışık simgesi veya P harfi ok işaretiyle",
    anlami: "Park/konum lambaları (yan lambalar) aktif.",
    nedenler: ["Sürücü park lambalarını açtı veya otomatik sistem devrede"],
    yapilacaklar: ["Uzun park halinde aküyü korumak için lambayı kapat"],
    servis_gerekli: false,
    anahtar_kelimeler: ["park lambası", "konum lambası", "sidelight"],
  },
];

// ─── Tüm semboller birleşik liste ─────────────────────────────────────────────

export const TUM_IKAZ_SEMBOLLERI: IkazSembolu[] = [
  ...KIRMIZI_IKAZLAR,
  ...SARI_UYARILAR,
  ...BILGI_LAMBALARI,
  ...T10F_OZGUL,
  ...ILAVE_KIRMIZI_IKAZLAR,
  ...ILAVE_SARI_UYARILAR,
  ...ILAVE_BILGI_LAMBALARI,
];

// Görsel eşleştirme için Claude'a gönderilecek özet liste
export const SEMBOL_OZET_LISTESI = TUM_IKAZ_SEMBOLLERI.map((s) => ({
  id: s.id,
  ad: s.ad,
  renk: s.renk,
  sembol_tanimi: s.sembol_tanimi,
}));

export const ACILIYET_ETIKETLER: Record<AciliyetDuzeyi, string> = {
  hemen_dur: "Hemen Dur!",
  yakin_servis: "Yakın Servise Git",
  dikkat: "Dikkat Et",
  bilgi: "Bilgi",
};

export const RENK_SINIF: Record<IkazRengi, { bg: string; text: string; border: string; badge: string }> = {
  kirmizi: {
    bg: "bg-red-50 dark:bg-red-950/20",
    text: "text-red-600 dark:text-red-400",
    border: "border-red-200 dark:border-red-800",
    badge: "bg-red-100 text-red-700 dark:bg-red-900/50 dark:text-red-300",
  },
  sari: {
    bg: "bg-amber-50 dark:bg-amber-950/20",
    text: "text-amber-600 dark:text-amber-400",
    border: "border-amber-200 dark:border-amber-800",
    badge: "bg-amber-100 text-amber-700 dark:bg-amber-900/50 dark:text-amber-300",
  },
  yesil: {
    bg: "bg-green-50 dark:bg-green-950/20",
    text: "text-green-600 dark:text-green-400",
    border: "border-green-200 dark:border-green-800",
    badge: "bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300",
  },
  mavi: {
    bg: "bg-blue-50 dark:bg-blue-950/20",
    text: "text-blue-600 dark:text-blue-400",
    border: "border-blue-200 dark:border-blue-800",
    badge: "bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300",
  },
  beyaz: {
    bg: "bg-neutral-50 dark:bg-neutral-900",
    text: "text-neutral-600 dark:text-neutral-400",
    border: "border-neutral-200 dark:border-neutral-700",
    badge: "bg-neutral-100 text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300",
  },
};

export const ACILIYET_RENK: Record<AciliyetDuzeyi, string> = {
  hemen_dur: "bg-red-600 text-white",
  yakin_servis: "bg-orange-500 text-white",
  dikkat: "bg-amber-400 text-amber-900",
  bilgi: "bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300",
};
