export type IkazRengi = "kirmizi" | "sari" | "mavi" | "yesil" | "beyaz";
export type AciliyetDuzeyi = "hemen_dur" | "yakin_servis" | "dikkat" | "bilgi";
export type ModelUyumu = "t10x" | "t10f" | "hepsi";

export interface IkazSembolu {
  id: string;
  ad: string;
  renk: IkazRengi;
  aciliyet: AciliyetDuzeyi;
  model: ModelUyumu;
  sembol_tanimi: string; // Claude'a gönderilecek görsel açıklama
  gorsel?: string; // /ikaz/ klasöründeki PNG dosyası
  kitapcik_aciklama: string; // Togg kullanma kılavuzundaki kısa resmi açıklama
  anlami: string; // Detaylı açıklama
  nedenler: string[];
  yapilacaklar: string[];
  servis_gerekli: boolean;
  not?: string;
  anahtar_kelimeler: string[];
}

// ─── Kırmızı İkazlar (Acil — Hemen Dur) ─────────────────────────────────────

const KIRMIZI_IKAZLAR: IkazSembolu[] = [
  {
    id: "park-freni-ariza",
    ad: "Elektromekanik Park Freni Arızası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img17.png",
    sembol_tanimi: "Kırmızı renkte daire içinde P harfi — yanıp söner",
    kitapcik_aciklama: "Elektromekanik park freninde arıza var.",
    anlami: "Elektromekanik park freni arızası.",
    nedenler: [
      "Park freni aktüatörü arızası",
      "Park freni sensör hatası",
      "Elektrik sistemi sorunu",
    ],
    yapilacaklar: [
      "Vitesi P konumuna al, düz zeminde park et",
      "Togg yetkili servisine git",
      "Eğimli zeminde araç bırakma",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["park freni arıza", "el freni arıza", "EPB arıza"],
  },
  {
    id: "hava-yastigi",
    ad: "Hava Yastığı Sistem Hatası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img12.png",
    sembol_tanimi: "Kırmızı renkte, önünde yuvarlak balon olan oturan insan silüeti",
    kitapcik_aciklama: "Hava yastığı/emniyet kemeri ön gergi sisteminde arıza var.",
    anlami: "Hava yastığı sistem hatası. Kaza anında hava yastıkları çalışmayabilir.",
    nedenler: [
      "SRS kontrol ünitesi arızası",
      "Hava yastığı sensör bağlantı sorunu",
      "Akü bağlantısı kesildikten sonra hata kodu oluşması",
      "Araç fiziksel hasar görmüş",
    ],
    yapilacaklar: [
      "Sürüşe devam edebilirsin ancak kaza riskini göz önünde bulundur",
      "En kısa sürede yetkili Togg servisine git",
      "Sistemi kendin sıfırlamaya ya da müdahale etmeye çalışma",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["hava yastığı", "airbag", "SRS", "emniyet kemeri"],
  },
  {
    id: "motor-ariza",
    ad: "Motor Sistemi Hatası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page2_img19.jpeg",
    sembol_tanimi: "Kırmızı renkte araç yan silüeti gövdesi, içinde veya yanında ünlem işareti (!) — bagaj kapalı, araç tam silüeti",
    kitapcik_aciklama: "Güç aktarma organı sisteminde arıza var.",
    anlami: "Motor sistemi hatası. Güç kaybı yaşanabilir.",
    nedenler: [
      "Tahrik motoru aşırı ısınması",
      "İnverter arızası",
      "Yüksek voltaj sistemi hatası",
      "Motor sargı hasarı",
    ],
    yapilacaklar: [
      "Güvenli bir yerde dur",
      "Aracı kapatıp 5 dakika bekle, yeniden başlatmayı dene",
      "Uyarı devam ederse Togg Care'i ara",
      "Aşırı sıcaklık söz konusuysa araçtan uzaklaş",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["motor", "tahrik", "arıza", "güç yok", "elektrik motoru"],
  },
  {
    id: "yuksek-voltaj",
    ad: "Yüksek Voltaj Sistemi Arızası",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page2_img21.png",
    sembol_tanimi: "Kırmızı renkte uyarı üçgeni içinde yıldırım işareti",
    kitapcik_aciklama: "Yüksek voltaj sisteminde arıza var.",
    anlami: "Yüksek voltaj sistemi arızası. Ciddi elektrik çarpması riski.",
    nedenler: [
      "Yüksek voltaj yalıtım arızası",
      "Batarya sızıntısı veya hasar",
      "Şarj sistemi kısa devre",
      "Kaza sonrası sistem güvenlik kilidinin devreye girmesi",
    ],
    yapilacaklar: [
      "Hemen dur, motoru kapat",
      "Araçtan uzaklaş — en az 10 metre",
      "Turuncu kabloları ve bileşenleri ASLA dokunma",
      "112 ve Togg Care'i ara",
    ],
    servis_gerekli: true,
    not: "Turuncu renkli kablo veya bileşenler 400V taşır. Dokunmayın.",
    anahtar_kelimeler: ["yüksek voltaj", "HV", "elektrik çarpması", "400V", "batarya hasar"],
  },
  {
    id: "guc-direksiyon",
    ad: "Elektrikli Direksiyon Hatası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img13.png",
    sembol_tanimi: "Kırmızı renkte direksiyon simidi içinde ünlem işareti",
    kitapcik_aciklama: "Elektrikli direksiyon sisteminde arıza var.",
    anlami: "Elektrikli direksiyon hatası. Direksiyonu döndürmek çok zorlaşabilir.",
    nedenler: [
      "EPS kontrol ünitesi arızası",
      "Direksiyon motor sensör hatası",
      "12V yardımcı akü zayıf veya boş",
      "Direksiyon mili mekanik sorunu",
    ],
    yapilacaklar: [
      "Güvenli hızda yavaşla, dikkatli sürdür",
      "Direksiyon ağırlaştığı için önceden dönüşleri planla",
      "Mümkün olan ilk fırsatta dur",
      "Yetkili servise çek",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["direksiyon", "EPS", "güç direksiyonu", "direksiyon ağır"],
  },
];

// ─── Sarı Uyarılar (Dikkat — Yakında Servis) ─────────────────────────────────

const SARI_UYARILAR: IkazSembolu[] = [
  {
    id: "lastik-basinc",
    ad: "Lastik Basınç Uyarısı (TPMS)",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img16.png",
    sembol_tanimi: "Sarı renkte, kesik çizgili zemin üzerinde duran ve içinde ünlem işareti olan lastik/tekerlek kesiti simgesi",
    kitapcik_aciklama: "Lastik basıncı düşük. Lastikleri kontrol edin.",
    anlami: "Bir veya birden fazla lastiğin basıncı önerilen değerin altında.",
    nedenler: [
      "Soğuk hava nedeniyle basınç düşüşü (normal)",
      "Yavaş lastik delinmesi",
      "Valf kapağı gevşemiş",
      "Lastik zararı",
    ],
    yapilacaklar: [
      "En yakın güvenli yerde dur, lastikleri görsel kontrol et",
      "Lastik basınç sensörünü (kapı kenarı etiketi) kontrol et: T10X ön 2.5 bar / arka 2.3 bar",
      "Uygun basınca şişir",
      "15 km/s üzerinde sürmeden önce basıncı düzelt",
    ],
    servis_gerekli: false,
    not: "Soğuk havada her 10°C düşüş için yaklaşık 0.1 bar basınç kaybı normaldir.",
    anahtar_kelimeler: ["lastik", "TPMS", "basınç", "patlak", "tekerlek"],
  },
  {
    id: "abs-ariza",
    ad: "ABS Sistemi Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page3_img16.png",
    sembol_tanimi: "Sarı renkte ABS yazısı, genellikle daire içinde",
    kitapcik_aciklama: "ABS sisteminde arıza var.",
    anlami: "Kilitlenme önleme fren sistemi devre dışı. Normal frenleme çalışır ama ani frende tekerlekler kilitlenebilir.",
    nedenler: [
      "ABS tekerlek hız sensörü arızası",
      "ABS kontrol ünitesi hatası",
      "Fren hidroliği baskı sensörü",
    ],
    yapilacaklar: [
      "Normal sürüşe devam edebilirsin",
      "Islak ve kaygan zeminde özellikle dikkatli ol",
      "Ani frenleme yaparsan tekerlekler kilitlenebilir — daha uzun mesafe bırak",
      "Yetkili serviste kontrol ettir",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["ABS", "kilitlenme", "fren", "kayma"],
  },
  {
    id: "esp-esc",
    ad: "Elektronik Denge Kontrolü Arızası / Devrede",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img3.png",
    sembol_tanimi: "Sarı renkte kayan araç silüeti — sabit yanıyorsa arıza, yanıp sönüyorsa devreye girdi",
    kitapcik_aciklama: "Elektronik denge kontrol sistemi devreye girdi veya arızalı.",
    anlami: "Denge kontrol sistemi müdahalede bulunuyor VEYA sistem devre dışı bırakıldı.",
    nedenler: [
      "Kaygan zeminde ESP devreye girdi (normal yanıp sönme)",
      "Sürücü tarafından devre dışı bırakıldı",
      "Sistem arızası (sabit yanarsa)",
    ],
    yapilacaklar: [
      "Sürekli yanıp sönüyorsa: kaygan zeminde, hızı düşür, düzgün sürdür",
      "Sabit yanıyorsa: sistem kapalı — ıslak zeminde dikkat",
      "Servis uyarısıyla birlikte yanıyorsa: yetkili servise git",
    ],
    servis_gerekli: false,
    not: "ESP lambası yanıp sönüyorsa sistem çalışıyor demektir — bu normal.",
    anahtar_kelimeler: ["ESP", "ESC", "denge", "kayma", "kayan araba"],
  },
  {
    id: "sarj-sistemi",
    ad: "Şarj Sistemi Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img14.png",
    sembol_tanimi: "Sarı renkte şarj fişi/konnektör simgesi veya yıldırım işareti ile birlikte ünlem",
    kitapcik_aciklama: "Şarj sisteminde arıza var.",
    anlami: "AC veya DC şarj sisteminde sorun var. Araç şarj olmayabilir.",
    nedenler: [
      "Şarj kablosu düzgün takılmamış",
      "OBC (şarj ünitesi) arızası",
      "Şarj soketi hasarlı",
      "Yazılım hatası",
    ],
    yapilacaklar: [
      "Kabloyu çıkar ve yeniden tak",
      "Farklı şarj istasyonu dene",
      "Aracı yeniden başlat",
      "Sorun devam ederse Togg Care'i ara",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["şarj", "şarj yok", "şarj olmaz", "kablo", "şarj sistemi"],
  },
  {
    id: "batarya-dusuk",
    ad: "Yüksek Voltajlı Batarya Şarjı Düşük",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    sembol_tanimi: "Sarı/turuncu renkte şarj fişi ve düşük batarya simgesi kombinasyonu",
    kitapcik_aciklama: "Yüksek voltajlı batarya şarj seviyesi düşük.",
    anlami: "Yüksek voltajlı batarya şarjı düşük. Yakında şarj gerekiyor.",
    nedenler: ["Uzun sürüş", "Soğuk hava kapasitesi etkisi"],
    yapilacaklar: [
      "Yakın şarj istasyonu bul (Togg Harita veya Trugo uygulaması)",
      "Gereksiz elektrikli ekipmanları kapat",
      "Yüksek hız ve ani hızlanmadan kaçın",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["batarya düşük", "az şarj", "sarı batarya", "menzil az"],
  },
  {
    id: "yikama-sivisi",
    ad: "Yıkama Sıvısı Seviyesi Düşük",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img3.png",
    sembol_tanimi: "Sarı renkte, yelpaze şeklinde sprey çıkan ön cam ve su damlaları simgesi",
    kitapcik_aciklama: "Cam yıkama sıvısı seviyesi düşük.",
    anlami: "Silecek suyu deposu boşalmak üzere.",
    nedenler: ["Depo uzun süredir doldurulmamış"],
    yapilacaklar: [
      "En yakın benzin istasyonu veya market'ten silecek suyu al",
      "Kışın donmayan silecek sıvısı kullan (-20°C)",
      "Depoyu doldur — T10X ön kaporta sol tarafta",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["silecek suyu", "cam suyu", "wiper", "cam yıkama"],
  },
  {
    id: "batarya-sicaklik",
    ad: "Termal Sistem Soğutucu Sıvı Düşük",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    sembol_tanimi: "Sarı/turuncu renkte soğutucu/termal sistem simgesi, içinde sıvı seviyesi göstergesi",
    kitapcik_aciklama: "Batarya termal yönetim sistemi uyarısı.",
    anlami: "Termal sistem soğutucu sıvı seviyesi düşük.",
    nedenler: [
      "Çok soğuk hava (batarya ön ısıtması gerekli)",
      "Uzun ve yüksek hızda sürüş sonrası aşırı ısınma",
      "Hızlı DC şarj sonrası sıcaklık yükselmesi",
    ],
    yapilacaklar: [
      "Soğuk havasada: 10-15 dakika bekle, batarya ısınır",
      "Sıcak havasada: gölge alanda park et, şarjı bekle",
      "Şarj hızı kısıtlandıysa normaldir — batarya korunuyor",
    ],
    servis_gerekli: false,
    not: "Batarya termal yönetim sistemi otomatik olarak devreye girer.",
    anahtar_kelimeler: ["batarya sıcak", "batarya soğuk", "ısınma", "sıcaklık", "thermal"],
  },
  {
    id: "park-freni",
    ad: "Elektromekanik Park Freni Etkin",
    renk: "kirmizi",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img18.png",
    sembol_tanimi: "Kırmızı/sarı renkte daire içinde P harfi — sabit yanıyorsa park freni etkin veya EBD uyarısı, yanıp sönüyorsa arıza",
    kitapcik_aciklama: "Elektromekanik park freni etkin veya elektronik fren kuvveti dağılımı uyarısı.",
    anlami: "Elektromekanik park freni etkin veya Elektronik fren kuvveti dağılımı uyarısı.",
    nedenler: [
      "Sürücü park freni açmayı unuttu",
      "Otomatik park freni aktif",
    ],
    yapilacaklar: [
      "Park freni butonuna bas ve serbest bırak",
      "Vites P konumuna al, freni bırak",
      "Uyarı kaybolmazsa Togg servisine git",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["park freni", "el freni", "P freni", "kırmızı P"],
  },
  {
    id: "motor-bakim",
    ad: "Motor Sistemi Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page2_img18.png",
    sembol_tanimi: "Sarı/turuncu renkte motor/araç gövdesi simgesi",
    kitapcik_aciklama: "Güç aktarma organı sisteminde uyarı.",
    anlami: "Motor sistemi uyarısı. Performans kısıtlaması olabilir.",
    nedenler: [
      "Çeşitli elektronik sistem hataları",
      "Sensör arızaları",
      "Yazılım hatası",
    ],
    yapilacaklar: [
      "Aracı kapatıp yeniden başlat",
      "Uyarı devam ederse yetkili servise git",
      "Togg Care ile iletişime geç — hata kodunu uzaktan okuyabilirler",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["servis", "arıza", "hata", "check", "genel uyarı"],
  },
];

// ─── Mavi / Yeşil Bilgi Lambaları ────────────────────────────────────────────

const BILGI_LAMBALARI: IkazSembolu[] = [
  {
    id: "sarj-aktif",
    ad: "Şarj Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page1_img19.png",
    sembol_tanimi: "Yeşil renkte şarj fişi simgesi veya yıldırım işareti — kablo bağlı görseli",
    kitapcik_aciklama: "Araç şarj oluyor.",
    anlami: "Araç başarıyla şarja bağlandı ve şarj oluyor.",
    nedenler: ["Şarj kablosu bağlı"],
    yapilacaklar: ["Şarj tamamlanana kadar bekle", "Trumore veya Togg uygulamasıyla şarj ilerlemesini takip et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["şarj oluyor", "şarj aktif", "yeşil şarj"],
  },
  {
    id: "uzun-far",
    ad: "Uzun Far Aktif",
    renk: "mavi",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img23.png",
    sembol_tanimi: "Mavi renkte, yatay çizgilerle sola doğru yayılan far ışığı simgesi",
    kitapcik_aciklama: "Uzun far açık.",
    anlami: "Uzun (yüksek) huzmeli farlar aktif.",
    nedenler: ["Sürücü uzun far devreye aldı veya otomatik far sistemi açtı"],
    yapilacaklar: [
      "Karşıdan araç geliyorsa uzun farı kapat",
      "Otomatik far açıksa: sistem karşıdan araç tespit ettiğinde kısa fara geçer",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["uzun far", "yüksek huzme", "far", "mavi far"],
  },
  {
    id: "serit-takip",
    ad: "Şerit Takip Asistanı Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img4.png",
    sembol_tanimi: "Yeşil renkte, iki şerit çizgisi arasında ortalanmış araç simgesi",
    kitapcik_aciklama: "Şerit takip asistanı aktif.",
    anlami: "Şerit takip asistanı aktif ve yol işaretlerini takip ediyor.",
    nedenler: ["ADAS sürücü destek sistemi açık"],
    yapilacaklar: ["Normal sürüşe devam et", "Direksiyon üzerinde ellerini tut"],
    servis_gerekli: false,
    anahtar_kelimeler: ["şerit", "lane assist", "şerit takip", "ADAS"],
  },
  {
    id: "adaptif-hiz",
    ad: "Adaptif Hız Sabitleyici Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page2_img8.png",
    sembol_tanimi: "Yeşil renkte hız göstergesi kadranı ve ok simgesi veya ACC yazısı",
    kitapcik_aciklama: "Adaptif hız sabitleyici aktif.",
    anlami: "Adaptif cruise control aktif. Araç önündeki araçla mesafeyi koruyarak hız ayarlıyor.",
    nedenler: ["Sürücü ACC sistemi devreye aldı"],
    yapilacaklar: [
      "Frene basınca veya direksiyonu yoğun çevirince devre dışı kalır",
      "Ayarlı hızı ve mesafeyi kontrol et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["cruise control", "ACC", "hız sabitleyici", "adaptif hız"],
  },
  {
    id: "ota-guncelleme",
    ad: "TruOS Yazılım Güncellemesi Mevcut",
    renk: "mavi",
    aciliyet: "bilgi",
    model: "hepsi",
    sembol_tanimi: "Mavi renkte daire yükleme oku veya bulut indirme simgesi — UPDATE veya OTA yazısı",
    kitapcik_aciklama: "Araç yazılım güncellemesi mevcut.",
    anlami: "Araç için yeni bir yazılım güncellemesi hazır. İndirildi veya indiriliyor.",
    nedenler: ["Togg yeni TruOS sürümü yayınladı"],
    yapilacaklar: [
      "Aracı şarja bağla (%20 üzeri şarj gerekli)",
      "Wi-Fi'ye bağlan (veya hücresel ağ)",
      "Araç park halinde olmalı",
      "Güncelleme 30-60 dk sürebilir",
    ],
    servis_gerekli: false,
    not: "Güncelleme sırasında aracı kapatma veya kullanma.",
    anahtar_kelimeler: ["güncelleme", "OTA", "TruOS", "yazılım"],
  },
];

// ─── T10F'ye Özgü Semboller ───────────────────────────────────────────────────

const T10F_OZGUL: IkazSembolu[] = [
  {
    id: "yaya-koruma",
    ad: "Aktif Yaya Koruma Sistemi Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "t10f",
    sembol_tanimi: "Sarı renkte yürüyen insan silüeti ve kalkan/koruma simgesi",
    kitapcik_aciklama: "Aktif yaya koruma sisteminde arıza var.",
    anlami: "T10F'ye özgü aktif yaya koruma sistemi (kaput yükseltme) arızalı.",
    nedenler: [
      "Kaput aktüatörü arızası",
      "Yaya algılama sensörü hatası",
    ],
    yapilacaklar: [
      "Yetkili Togg servisine git",
      "Sistemin devre dışı kalması kaza anında yaya korumasını azaltır",
    ],
    servis_gerekli: true,
    not: "Bu sistem yalnızca T10F'de bulunur, T10X'te yoktur.",
    anahtar_kelimeler: ["yaya koruma", "kaput", "aktif güvenlik", "T10F"],
  },
  {
    id: "awd-sistem",
    ad: "AWD / 4More Sistem Uyarısı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "t10f",
    sembol_tanimi: "Sarı renkte dört tekerlekli araç üstten görünüm veya 4WD / AWD yazısı",
    kitapcik_aciklama: "AWD sisteminde arıza var.",
    anlami: "İki motorlu AWD sisteminde hata. Tek motora düşürülmüş olabilir.",
    nedenler: [
      "Arka motor kontrol ünitesi arızası",
      "AWD tork dağıtım sistemi hatası",
      "Yüksek sıcaklık nedeniyle geçici kısıtlama",
    ],
    yapilacaklar: [
      "Aracı kapatıp 10 dakika bekle — termal ise kendiliğinden geçer",
      "Devam ederse yetkili servise git",
    ],
    servis_gerekli: true,
    not: "T10F AWD versiyonuna özgü semboldür.",
    anahtar_kelimeler: ["AWD", "4More", "4x4", "çift motor", "T10F AWD"],
  },
];

// ─── Ek Kırmızı Kritik İkazlar ───────────────────────────────────────────────

const ILAVE_KIRMIZI_IKAZLAR: IkazSembolu[] = [
  {
    id: "emniyet-kemeri",
    ad: "Emniyet Kemeri Takılı Değil veya Hata",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page1_img24.jpeg",
    sembol_tanimi: "Kırmızı renkte oturan insan silüeti, göğüs hizasında çapraz emniyet kemeri çizgisi — sabit veya yanıp söner",
    kitapcik_aciklama: "Emniyet kemeri takılı değil.",
    anlami: "Emniyet kemeri takılı değil veya hata. Sabit yanıyorsa hata, yanıp sönüyorsa kemer takılmamış.",
    nedenler: [
      "Emniyet kemeri takılmamış",
      "Emniyet kemeri tokası arızalı",
      "Emniyet kemeri sensörü hatası",
    ],
    yapilacaklar: [
      "Emniyet kemerini tak",
      "Yolcunun da kemerini taktığından emin ol",
      "Sorun devam ederse servise git",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["emniyet kemeri", "kemer", "seatbelt"],
  },
  {
    id: "aku-hata",
    ad: "Düşük Voltajlı Akü Hatası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img6.png",
    sembol_tanimi: "Kırmızı renkte dikdörtgen akü gövdesi, üstünde artı (+) ve eksi (-) terminaller",
    kitapcik_aciklama: "Düşük voltajlı akü sisteminde arıza var.",
    anlami: "Düşük voltajlı akü hatası. 12V yardımcı akü arızalı, elektronik sistemler etkilenebilir.",
    nedenler: [
      "Akü ömrü dolmuş",
      "Alternatör/şarj sistemi arızası",
      "Akü bağlantıları gevşemiş",
    ],
    yapilacaklar: [
      "Aracı güvenli yerde park et",
      "Togg Care'i ara: 0 850 222 86 44",
      "Yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["akü", "batarya", "12V", "akü hatası"],
  },
  {
    id: "termal-hata",
    ad: "Termal Sistem Hatası",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page2_img22.png",
    sembol_tanimi: "Kırmızı renkte motor/ısı değiştirgeci bloğu simgesi ile ısı dalgaları",
    kitapcik_aciklama: "Termal yönetim sisteminde kritik arıza var.",
    anlami: "Batarya veya motor soğutma sistemi kritik arızada. Aşırı ısınma riski var.",
    nedenler: [
      "Soğutucu sıvı seviyesi kritik düşük",
      "Termal yönetim sistemi arızası",
      "Soğutma pompası hatası",
    ],
    yapilacaklar: [
      "Hemen güvenli yerde dur",
      "Motoru kapat",
      "Soğuyana kadar bekle",
      "Togg Care'i ara",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["termal", "ısınma", "soğutma", "thermal"],
  },
  {
    id: "hv-yangin",
    ad: "Yüksek Voltajlı Batarya Yangın Uyarısı",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page4_img26.jpeg",
    sembol_tanimi: "Kırmızı renkte uyarı üçgeni, batarya yangın mesajı ekranda görünür",
    kitapcik_aciklama: "Batarya paketi yangın uyarısı. Araçtan derhal uzaklaşın.",
    anlami: "Sistem bataryada yangın tespit etti. DERHAL araçtan uzaklaş.",
    nedenler: [
      "Batarya termal kaçak (thermal runaway)",
      "Fiziksel hasar",
      "Şarj sistemi arızası",
    ],
    yapilacaklar: [
      "HEMEN dur ve aracı terk et — en az 50 metre uzaklaş",
      "112 ara",
      "Yakınına geçme",
      "Togg Care: 0 850 222 86 44",
    ],
    servis_gerekli: true,
    not: "Bu uyarı ekranda metin mesajı olarak da görünür. Araçtan derhal uzaklaş, kesinlikle geri dönme.",
    anahtar_kelimeler: ["yangın", "batarya yangın", "thermal runaway", "fire"],
  },
  {
    id: "ecall-ariza",
    ad: "eCall Acil Çağrı Sistemi Arızası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page4_img7.png",
    sembol_tanimi: "Kırmızı renkte SOS yazısı, bağlantı/telefon simgesiyle birlikte",
    kitapcik_aciklama: "Acil çağrı sisteminde arıza var.",
    anlami: "Araç içi acil çağrı sistemi (eCall) arızalı. Kaza anında otomatik acil çağrı yapılamaz.",
    nedenler: [
      "eCall modül arızası",
      "SIM kart sorunu",
      "Anten bağlantı hatası",
    ],
    yapilacaklar: [
      "Yetkili Togg servisine git",
      "Acil durumda telefonunuzla 112'yi arayın",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["eCall", "acil çağrı", "SOS", "112"],
  },
  {
    id: "fren-servo",
    ad: "Fren Servosu Servis Uyarısı",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    sembol_tanimi: "Kırmızı renkte daire içinde ünlem işareti — akıllı fren servosu veya rejeneratif fren kontrol uyarısı",
    kitapcik_aciklama: "Akıllı fren servosu sisteminde arıza var.",
    anlami: "Akıllı fren servosu veya rejeneratif fren sistemi servis gerektiriyor.",
    nedenler: [
      "Fren servo arızası",
      "Rejeneratif fren sistemi hatası",
      "Fren kontrol ünitesi sorunu",
    ],
    yapilacaklar: [
      "Frenleme mesafeni artır",
      "Hız düşür",
      "Yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["fren servo", "rejeneratif fren", "fren kontrol"],
  },
  {
    id: "elektrikli-bagaj",
    ad: "Elektrikli Bagaj Kapağı Arızası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img22.jpeg",
    sembol_tanimi: "Kırmızı renkte araç yan silüeti, arka bagaj kapağı açık konumda gösterilmiş",
    kitapcik_aciklama: "Elektrikli bagaj kapağı sisteminde arıza var.",
    anlami: "Elektrikli bagaj kapağı sistemi arızalı. Kapak tam kapanmıyor veya motor sistemi çalışmıyor.",
    nedenler: [
      "Bagaj kapağı aktüatörü arızası",
      "Bagaj kilidi sensörü hatası",
      "Elektrik sistemi sorunu",
      "Mekanik engel veya hasar",
    ],
    yapilacaklar: [
      "Bagajın tam kapandığını kontrol et",
      "Manuel olarak kapat ve kilitlemeyi dene",
      "Sürüş sırasında bagaj açıksa hemen dur",
      "Yetkili Togg servisine git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["bagaj", "elektrikli bagaj", "bagaj kapağı", "bagaj arıza", "arka kapak"],
  },
];

// ─── Ek Sarı Uyarılar ────────────────────────────────────────────────────────

const ILAVE_SARI_UYARILAR: IkazSembolu[] = [
  {
    id: "fren-sivisi",
    ad: "Fren Sıvısı Seviyesi Düşük",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img9.png",
    sembol_tanimi: "Sarı renkte daire içinde ünlem — fren hidroliği uyarısı",
    kitapcik_aciklama: "Fren hidrolik sıvısı seviyesi düşük.",
    anlami: "Fren hidrolik sıvısı seviyesi düşük. Frenleme performansı etkilenebilir.",
    nedenler: [
      "Fren sıvısı kaçağı",
      "Fren balatası aşıması nedeniyle seviye düşüşü",
      "Servis zamanı geldi",
    ],
    yapilacaklar: [
      "Hızı düşür, güvenli yerde dur",
      "Fren sıvısı seviyesini kontrol et (kaputu açma)",
      "Togg servisi çağır",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["fren sıvısı", "hidrolik", "brake fluid"],
  },
  {
    id: "yolcu-hava-yastigi",
    ad: "Ön Yolcu Hava Yastığı Devre Dışı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img5.png",
    sembol_tanimi: "Sarı renkte oturan yolcu figürü, üzerinde çarpı işareti veya 2 rakamı",
    kitapcik_aciklama: "Ön yolcu hava yastığı devre dışı bırakıldı.",
    anlami: "Ön yolcu koltuğu hava yastığı devre dışı bırakılmış veya arızalı.",
    nedenler: [
      "Çocuk koltuğu algılama sistemi devrede bırakıldı",
      "Yolcu koltuğu boş/sensör hatası",
      "Manuel devre dışı bırakma",
    ],
    yapilacaklar: [
      "Ön koltuğa çocuk koltuğu takılıysa bu normaldir",
      "Aksi halde yetkili servise git",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["yolcu hava yastığı", "airbag kapalı", "ön yolcu"],
  },
  {
    id: "aku-zayif",
    ad: "Düşük Voltajlı Akü Şarj Durumu Zayıf",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img7.png",
    sembol_tanimi: "Sarı renkte dikdörtgen akü gövdesi, artı ve eksi terminaller, düşük şarj göstergesi",
    kitapcik_aciklama: "Düşük voltajlı akü şarj seviyesi zayıf.",
    anlami: "12V yardımcı akü şarj seviyesi zayıf. Elektronik sistemlerde gecikmeli tepki olabilir.",
    nedenler: [
      "Uzun süre park halinde kullanım",
      "Akü yaşlanması",
      "Şarj sistemi verimsizliği",
    ],
    yapilacaklar: [
      "En kısa sürede kısa bir sürüş yap veya aracı şarja bağla",
      "Sorun tekrarlarsa servise git",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["akü zayıf", "12V zayıf", "yardımcı akü"],
  },
  {
    id: "isik-ariza",
    ad: "Işık Arızası",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img8.png",
    sembol_tanimi: "Sarı renkte far veya ampul simgesi, etrafında ışık ışınları ve uyarı göstergesi",
    kitapcik_aciklama: "Dış aydınlatmada arıza var.",
    anlami: "Araç aydınlatma sisteminde bir veya birden fazla ampul arızası.",
    nedenler: [
      "Far ampulü yanmış",
      "Stop veya sinyal lambası arızası",
      "LED far modülü hatası",
    ],
    yapilacaklar: [
      "Hangi lambanın arızalı olduğunu kontrol et",
      "Ampulü değiştir veya servise git",
      "Gece sürüşlerinde dikkat et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["ışık arızası", "ampul", "far arızası", "lamba"],
  },
  {
    id: "fren-balata",
    ad: "Fren Balatası Değiştir",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img25.png",
    sembol_tanimi: "Sarı renkte fren diski ve yıpranmış balata göstergesi olan simge",
    kitapcik_aciklama: "Fren balatalarını değiştirin.",
    anlami: "Fren balataları aşınma sınırına ulaştı. En kısa sürede değiştirilmeli.",
    nedenler: [
      "Balata ömrü doldu",
      "Aşınma sensörü tetiklendi",
    ],
    yapilacaklar: [
      "Yetkili Togg servisine git",
      "Erteleme — fren performansı düşük",
      "Frenleme mesafeni artır",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["fren balatası", "balata", "fren yıpranma"],
  },
  {
    id: "aeb-fcw",
    ad: "Gelişmiş Acil Frenleme / Ön Çarpışma Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    sembol_tanimi: "Sarı renkte önde araç ve çarpışma çizgileri — yanıp sönüyorsa uyarı, sabit yanıyorsa AEB devre dışı veya LIM PERF sınırlı performans",
    kitapcik_aciklama: "Gelişmiş acil fren sistemi uyarısı.",
    anlami: "Gelişmiş acil frenleme uyarısı veya çarpışma engelleyici devre dışı. Yanıp sönüyorsa ön çarpışma uyarısı.",
    nedenler: [
      "Önde araç/engel tespit edildi",
      "Sensör kirli veya engellenmiş",
      "Sistem manuel kapatılmış",
    ],
    yapilacaklar: [
      "Fren sistemini kontrol et",
      "Sensör ön camını temizle",
      "Güvenli mesafe bırak",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["AEB", "çarpışma önleme", "acil frenleme", "FCW"],
  },
  {
    id: "hv-batarya-dusuk",
    ad: "Yüksek Voltajlı Batarya Şarjı Düşük",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    sembol_tanimi: "Sarı renkte, içinde yıldırım/şimşek işareti olan batarya simgesi",
    kitapcik_aciklama: "Yüksek voltajlı batarya şarj seviyesi düşük. Araç kısa sürede şarj edilmelidir.",
    anlami: "Ana traksiyon bataryası şarj seviyesi düşük. Araç yakında hız kısıtlaması uygulayabilir.",
    nedenler: [
      "Batarya şarj seviyesi %10-%20 arasına düştü",
      "Soğuk hava kapasitesi etkisi",
    ],
    yapilacaklar: [
      "Yakın şarj istasyonu bul",
      "Hızı düşür",
      "Performans kısıtlı olacak",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["yüksek voltaj batarya", "HV batarya düşük", "traksiyon bataryası"],
  },
  {
    id: "motor-sinirli",
    ad: "Sınırlı Motor Performansı Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img11.png",
    sembol_tanimi: "Sarı renkte LIM PERF yazısı ile araç yan görünüm silüeti veya ünlem işareti — NOT: kaplumbağa simgesi değil, araç gövdesi simgesidir",
    kitapcik_aciklama: "Motor sistemi performans kısıtlaması uygulandı.",
    anlami: "Motor sistemi kısıtlı modda çalışıyor. Maksimum güç ve hız düşürülmüştür.",
    nedenler: [
      "Batarya veya motor aşırı ısınması",
      "HV sistem koruma modu",
      "Yazılım güvenlik kısıtlaması",
    ],
    yapilacaklar: [
      "Hızı azalt, klimayı kapat",
      "15-20 dakika soğuması için bekle",
      "Uyarı devam ederse Togg Care ara",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["sınırlı performans", "motor kısıtlı", "limp mode", "kaplumbağa modu"],
  },
  {
    id: "termal-sivisi",
    ad: "Termal Sistem Soğutucu Sıvı Düşük",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page2_img23.png",
    sembol_tanimi: "Sarı renkte motor/termal ünite simgesi, soğutucu sıvı seviye göstergesi veya termometre",
    kitapcik_aciklama: "Termal sistem soğutucu sıvısı düşük.",
    anlami: "Batarya/motor soğutma sistemi sıvı seviyesi düşük.",
    nedenler: [
      "Soğutucu sıvı kaçağı",
      "Buharlaşma",
      "Servis zamanı",
    ],
    yapilacaklar: [
      "Kaputu açma (basınç altında olabilir)",
      "Togg servisine git",
      "Soğutucu sıvıyı kendin ekleme",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["termal sıvı", "soğutucu", "coolant"],
  },
  {
    id: "kor-nokta",
    ad: "Kör Nokta Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img4.png",
    sembol_tanimi: "Sarı renkte araç yan görünümü, radar dalgaları veya nesne uyarı simgesiyle birlikte",
    kitapcik_aciklama: "Kör nokta izleme sistemi yan şeritte araç algıladı.",
    anlami: "Kör nokta izleme sistemi yan şeritte araç tespit etti. Dikkatli şerit değiştir.",
    nedenler: [
      "Yan şeritte araç var",
      "Kör nokta sensörü uyarısı",
    ],
    yapilacaklar: [
      "Ayna ve direkt bakışla kontrol et",
      "Acele şerit değiştirme",
      "Sinyal ver",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["kör nokta", "blind spot", "şerit değiştirme", "yan uyarı"],
  },
  {
    id: "buz-yol",
    ad: "Buzlu Yol Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page3_img15.png",
    sembol_tanimi: "Beyaz/sarı renkte kar tanesi veya buz kristali simgesi, yol/araç göstergesiyle",
    kitapcik_aciklama: "Buzlanma tehlikesi. Dikkatli kullanın.",
    anlami: "Dış sıcaklık 4°C'nin altında, yol yüzeyi buzlanma riski taşıyor.",
    nedenler: [
      "Hava sıcaklığı 4°C altına düştü",
      "Yol buzlanma riski",
    ],
    yapilacaklar: [
      "Hızı düşür",
      "Frenleme mesafesini artır",
      "Ani fren ve direksiyon hareketlerinden kaçın",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["buz", "kar", "kaygan yol", "buzlu", "ice road"],
  },
  {
    id: "oto-durdurma-ariza",
    ad: "Auto Hold Arızası",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    sembol_tanimi: "Sarı/kırmızı renkte AUTO HOLD yazısı koyu arka planda",
    kitapcik_aciklama: "Otomatik tutma sisteminde arıza var.",
    anlami: "Otomatik durdurma (Auto Hold) sistemi arızalı.",
    nedenler: [
      "Elektronik park freni hatası",
      "Fren sistemi elektronik arızası",
    ],
    yapilacaklar: [
      "Manuel park freni kullan",
      "Rampalarda ekstra dikkat",
      "Yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["auto hold", "otomatik durdurma", "AUTO HOLD arıza"],
  },
  {
    id: "uyku-tespit",
    ad: "Uyku Durumu Tespiti Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page4_img6.png",
    sembol_tanimi: "Sarı renkte göz simgesi, uyuklama tespit göstergesi",
    kitapcik_aciklama: "Sürücü dikkat uyarısı. Mola verin.",
    anlami: "Sürücü yorgunluk/uyku belirtisi gösteriyor. Mola tavsiye edilir.",
    nedenler: [
      "Uzun süre sürüş",
      "Yorgun sürücü davranışı tespit edildi",
    ],
    yapilacaklar: [
      "En yakın güvenli yerde dur ve mola ver",
      "En az 20 dakika dinlen",
      "Çay/kahve iç",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["uyku", "yorgunluk", "drowsiness", "mola"],
  },
];

// ─── Ek Bilgi Lambaları ───────────────────────────────────────────────────────

const ILAVE_BILGI_LAMBALARI: IkazSembolu[] = [
  {
    id: "sarj-kablosu",
    ad: "Şarj Kablosu Takılı",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page1_img15.jpeg",
    sembol_tanimi: "Yeşil renkte şarj kablosu/konnektör fişi simgesi",
    kitapcik_aciklama: "Şarj kablosu bağlı.",
    anlami: "Şarj kablosu araca takılı. Araç şarj modunda ya da araç kilitli değilken kablo takılı.",
    nedenler: [
      "Şarj kablosu bağlı",
      "Şarj tamamlandı ve kablo hâlâ takılı",
    ],
    yapilacaklar: [
      "Şarj tamamlanınca kabloyu çıkar",
      "Park yerine göre kabloyu güvenli bırakabilirsin",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["şarj kablosu", "kablo takılı", "charge cable"],
  },
  {
    id: "suruse-hazir",
    ad: "Sürüşe Hazır (HAZIR)",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img19.png",
    sembol_tanimi: "Yeşil renkte HAZIR yazısı koyu arka planda",
    kitapcik_aciklama: "Araç sürüşe hazır.",
    anlami: "Araç sürüşe hazır durumda. Motor sistemi aktif, sürüş mümkün.",
    nedenler: ["Araç çalıştırıldı ve hazır"],
    yapilacaklar: ["Normal sürüşe devam edebilirsin"],
    servis_gerekli: false,
    anahtar_kelimeler: ["HAZIR", "sürüşe hazır", "ready"],
  },
  {
    id: "kisa-far",
    ad: "Kısa Far Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img2.png",
    sembol_tanimi: "Yeşil/mavi renkte, yatay çizgilerle sola doğru yayılan ve alt kısımda kesik çizgili far ışığı simgesi (kısa huzme)",
    kitapcik_aciklama: "Kısa far açık.",
    anlami: "Düşük huzmeli (kısa) farlar aktif.",
    nedenler: ["Far sistemi açık, kısa far seçili"],
    yapilacaklar: [
      "Normal sürüşe devam et",
      "Karanlıkta ve tünelde farlar açık olmalı",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["kısa far", "dipped headlights", "düşük huzme"],
  },
  {
    id: "yokus-inis",
    ad: "Yokuş İniş Kontrolü Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    sembol_tanimi: "Yeşil renkte eğimli zeminde inen araç simgesi, yokuş iniş sembolü",
    kitapcik_aciklama: "Yokuş iniş kontrolü aktif.",
    anlami: "Yokuş iniş kontrolü (HDC) aktif. Araç inişte sabit düşük hız korur.",
    nedenler: [
      "Sürücü HDC sistemi etkinleştirdi",
      "Dik iniş algılandı",
    ],
    yapilacaklar: [
      "Normal sürüşe devam et",
      "Fren gerekmeden araç hızını kontrol eder",
      "Çıkmak için butona bas",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["yokuş iniş", "HDC", "eğim kontrolü", "iniş kontrol"],
  },
  {
    id: "hiz-sabitleyici",
    ad: "Hız Sabitleyici Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page2_img10.png",
    sembol_tanimi: "Yeşil renkte hız kadranı/göstergesi simgesi, cruise control aktif göstergesi",
    kitapcik_aciklama: "Hız sabitleyici aktif.",
    anlami: "Standart hız sabitleyici (cruise control) aktif.",
    nedenler: ["Sürücü cruise control devreye aldı"],
    yapilacaklar: [
      "Fren veya gaz ile devre dışı kalır",
      "Etkin hızı kontrol et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["cruise control", "hız sabitleyici", "CC aktif"],
  },
  {
    id: "oto-durdurma",
    ad: "Auto Hold Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    sembol_tanimi: "Yeşil renkte AUTO HOLD yazısı koyu arka planda",
    kitapcik_aciklama: "Otomatik tutma sistemi aktif.",
    anlami: "Otomatik durdurma (Auto Hold) aktif. Araç durakta veya kırmızı ışıkta otomatik tutulur.",
    nedenler: ["Auto Hold sistemi sürücü tarafından etkinleştirildi"],
    yapilacaklar: [
      "Gaz pedalına basınca araç hareket eder",
      "Normal sürüşe devam et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["auto hold", "otomatik durdurma aktif"],
  },
  {
    id: "sag-sinyal",
    ad: "Sağ Sinyal Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img17.png",
    sembol_tanimi: "Yeşil renkte sağa dönen ok işareti",
    kitapcik_aciklama: "Sağ dönüş sinyali aktif.",
    anlami: "Sağ sinyal lambası çalışıyor.",
    nedenler: ["Sürücü sağ sinyal verdi"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["sağ sinyal", "sinyalizasyon", "dönüş lambası"],
  },
  {
    id: "sol-sinyal",
    ad: "Sol Sinyal Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img18.png",
    sembol_tanimi: "Yeşil renkte sola dönen ok işareti",
    kitapcik_aciklama: "Sol dönüş sinyali aktif.",
    anlami: "Sol sinyal lambası çalışıyor.",
    nedenler: ["Sürücü sol sinyal verdi"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["sol sinyal", "sinyalizasyon", "dönüş lambası"],
  },
  {
    id: "uzun-far-asistan",
    ad: "Uzun Far Asistanı Aktif",
    renk: "mavi",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img22.png",
    sembol_tanimi: "Mavi renkte, yatay çizgilerle sola doğru yayılan far ışığı ve daire içinde A harfi",
    kitapcik_aciklama: "Otomatik uzun far asistanı aktif.",
    anlami: "Otomatik uzun far sistemi aktif. Karşıdan araç gelince otomatik kısa fara geçer.",
    nedenler: ["Otomatik far sistemi açık"],
    yapilacaklar: [
      "Normal sürüşe devam et",
      "Sistem karşı araç gelince otomatik kısar",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["uzun far asistanı", "otomatik far", "auto high beam"],
  },
  {
    id: "sis-far",
    ad: "Sis Farı Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img10.png",
    sembol_tanimi: "Yeşil veya sarı renkte, eğimli çizgilerle yayılan far simgesi ve üç yatay dalga çizgisi (sis)",
    kitapcik_aciklama: "Sis farı açık.",
    anlami: "Ön veya arka sis farı aktif.",
    nedenler: ["Sürücü sis farını açtı"],
    yapilacaklar: [
      "Sis yokken sis farını kapat (gözleri kamaştırabilir)",
      "Sis geçince normal fara dön",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["sis farı", "fog light", "sis lambası"],
  },
  {
    id: "park-lambasi",
    ad: "Park Lambası / Konum Lambası Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img9.png",
    sembol_tanimi: "Yeşil renkte iki köşe ışık simgesi veya P harfi ok işaretiyle",
    kitapcik_aciklama: "Park lambası açık.",
    anlami: "Park/konum lambaları (yan lambalar) aktif.",
    nedenler: ["Sürücü park lambalarını açtı veya otomatik sistem devrede"],
    yapilacaklar: ["Uzun park halinde aküyü korumak için lambayı kapat"],
    servis_gerekli: false,
    anahtar_kelimeler: ["park lambası", "konum lambası", "sidelight"],
  },
];

// ─── Kaplumbağa / Performans Kısıtlama Sembolleri ────────────────────────────

const KAPLUMBAGA_SEMBOLLERI: IkazSembolu[] = [
  {
    id: "kaplumbaga-kritik",
    ad: "Kritik Performans Kısıtlaması (Kırmızı Kaplumbağa)",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page2_img17.png",
    sembol_tanimi: "Kırmızı renkte daire içinde kaplumbağa simgesi",
    kitapcik_aciklama: "Güç aktarma organı sistemi kritik performans kısıtlaması uygulandı.",
    anlami: "Araç kritik düzeyde sınırlı performans moduna geçti. Güç çok düşük, hız kısıtlı.",
    nedenler: [
      "Motor veya batarya aşırı ısınması",
      "Yüksek voltaj sistem arızası",
      "Termal yönetim sistemi kritik uyarısı",
    ],
    yapilacaklar: [
      "Hemen güvenli bir yere çek ve dur",
      "Motoru kapat, 15-20 dakika soğumaya bırak",
      "Togg Care'i ara: 0 850 222 86 44",
    ],
    servis_gerekli: true,
    not: "Kırmızı kaplumbağa sarı kaplumbağadan daha ciddidir — aracı mümkün olan ilk yerde durdur.",
    anahtar_kelimeler: ["kaplumbağa", "kırmızı kaplumbağa", "turtle mode", "kritik kısıtlama", "güç yok"],
  },
  {
    id: "kaplumbaga-sinirli",
    ad: "Sınırlı Performans Modu (Sarı Kaplumbağa)",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img12.png",
    sembol_tanimi: "Sarı renkte daire içinde kaplumbağa simgesi",
    kitapcik_aciklama: "Motor sistemi sınırlı performans modunda çalışıyor.",
    anlami: "Araç korumalı sınırlı performans moduna girdi. Güç ve hız kısıtlandı.",
    nedenler: [
      "Batarya veya motor ısındı, sistem koruma altına aldı",
      "Soğuk havada batarya kapasitesi düştü",
      "HV sistem yazılım güvenlik kısıtlaması",
    ],
    yapilacaklar: [
      "Hızı düşür, klimayı kapat",
      "15-20 dakika gölgede bekle",
      "Uyarı geçmezse Togg Care'i ara",
    ],
    servis_gerekli: false,
    not: "Sarı kaplumbağa genellikle geçicidir — araç soğuyunca normale döner.",
    anahtar_kelimeler: ["kaplumbağa", "sarı kaplumbağa", "turtle mode", "sınırlı performans", "limp mode"],
  },
];

// ─── Sürücü Destek Sistemi Sembolleri (ADAS) ──────────────────────────────────

const ADAS_SEMBOLLERI: IkazSembolu[] = [
  {
    id: "acc-standby",
    ad: "Adaptif Hız Sabitleyici Bekleme (Gri)",
    renk: "beyaz",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page2_img6.png",
    sembol_tanimi: "Gri/beyaz renkte araç silüeti + aşağı ok + hız kadranı",
    kitapcik_aciklama: "Adaptif hız sabitleyici bekleme modunda.",
    anlami: "Adaptif hız sabitleyici (ACC) bekleme konumunda — aktif değil.",
    nedenler: ["Sistem açık ama hız ayarlanmamış"],
    yapilacaklar: ["Hız ayarlamak için direksiyondaki butonu kullan"],
    servis_gerekli: false,
    anahtar_kelimeler: ["ACC standby", "adaptif hız bekleme", "cruise control kapalı"],
  },
  {
    id: "acc-uyari",
    ad: "Adaptif Hız Sabitleyici Uyarısı (Sarı)",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img7.png",
    sembol_tanimi: "Sarı renkte araç silüeti + aşağı ok + hız kadranı",
    kitapcik_aciklama: "Adaptif hız sabitleyici devre dışı kaldı.",
    anlami: "ACC sistemi uyarı durumunda — önde engel var veya sistem devre dışı.",
    nedenler: [
      "Çok yakın mesafede araç algılandı",
      "Hız çok düşük, sistem çalışamıyor",
    ],
    yapilacaklar: ["Fren yap, güvenli mesafe sağla", "Gerekirse sistemi yeniden etkinleştir"],
    servis_gerekli: false,
    anahtar_kelimeler: ["ACC uyarı", "adaptif hız uyarı", "cruise control devre dışı"],
  },
  {
    id: "pilot-assist-standby",
    ad: "Pilot Assist Bekleme",
    renk: "beyaz",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page2_img15.png",
    sembol_tanimi: "Beyaz/gri renkte araç şerit çizgileri arasında + hız kadranı",
    kitapcik_aciklama: "Pilot assist sistemi bekleme modunda.",
    anlami: "Pilot assist (ACC + şerit takip kombine) bekleme konumunda.",
    nedenler: ["Sistem açık ama tam aktif değil"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["pilot assist", "şerit+ACC standby", "ADAS bekleme"],
  },
  {
    id: "pilot-assist-uyari",
    ad: "Pilot Assist Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img16.png",
    sembol_tanimi: "Sarı renkte araç şerit çizgileri arasında + hız kadranı",
    kitapcik_aciklama: "Pilot assist sistemi devreye giremedi veya uyarı veriyor.",
    anlami: "Pilot assist sistemi uyarı durumunda. Şerit çizgileri algılanamıyor olabilir.",
    nedenler: ["Şerit çizgisi yok veya bozuk", "Sensör görüşü engellenmiş", "Hava koşulları"],
    yapilacaklar: [
      "Direksiyonu kontrol et",
      "Sensör camını temizle",
      "Sistemi devre dışı bırakıp yeniden etkinleştir",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["pilot assist uyarı", "şerit+ACC uyarı"],
  },
  {
    id: "serit-takip-standby",
    ad: "Şerit Takip Asistanı Bekleme",
    renk: "sari",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img6.png",
    sembol_tanimi: "Sarı renkte araç şerit çizgileri arasında (açık arka plan) — bekleme",
    kitapcik_aciklama: "Şerit takip asistanı bekleme modunda.",
    anlami: "Şerit takip asistanı aktif ama müdahale etmiyor.",
    nedenler: ["Sistem açık, şeritler algılanıyor, müdahale gerekmedi"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["şerit takip standby", "lane assist bekleme"],
  },
  {
    id: "serit-ihlali",
    ad: "Şerit İhlali Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page3_img7.png",
    sembol_tanimi: "Sarı renkte araç şerit çizgileri arasında + ünlem işareti",
    kitapcik_aciklama: "Araç şerit çizgisine yaklaştı, uyarı verildi.",
    anlami: "Araç şerit çizgisine yaklaşıyor veya geçiyor. Sinyal verilmeden şerit değişimi.",
    nedenler: ["Sinyal verilmeden şerit değişimi", "Rüzgar veya sürücü dikkatsizliği"],
    yapilacaklar: ["Direksiyonu ortalaya çek", "Şerit değiştirmeden önce sinyal ver"],
    servis_gerekli: false,
    anahtar_kelimeler: ["şerit ihlali", "lane departure", "şerit uyarısı"],
  },
  {
    id: "surucuye-dikkat-uyari",
    ad: "Sürücüye Dikkat Et Uyarısı (Kırmızı)",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page3_img11.png",
    sembol_tanimi: "Kırmızı renkte direksiyon simidi üzerinde iki el simgesi",
    kitapcik_aciklama: "Sürücü direksiyona ellerini koymalı — kritik uyarı.",
    anlami: "Pilot assist sistemi direksiyonda el algılamadı, kritik uyarı veriyor.",
    nedenler: [
      "Eller uzun süre direksiyon üzerinde değil",
      "Sürücü yorgunluk veya dikkatsizlik tespiti",
    ],
    yapilacaklar: [
      "Hemen direksiyona elleri koy",
      "Dikkatini topar",
      "Güvenli yerde mola ver",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["eller direksiyon", "sürücü uyarı", "hands on wheel", "dikkat"],
  },
  {
    id: "surucuye-dikkat-standby",
    ad: "Sürücüye Dikkat Et (Beyaz)",
    renk: "beyaz",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img10.png",
    sembol_tanimi: "Beyaz/gri renkte direksiyon simidi üzerinde iki el simgesi",
    kitapcik_aciklama: "Direksiyona ellerini koymanız gerekiyor.",
    anlami: "Sistem direksiyona el koyulmasını hatırlatıyor (bekleme düzeyi).",
    nedenler: ["Pilot assist aktif, el dokunuşu gerekiyor"],
    yapilacaklar: ["Direksiyona elleri koy"],
    servis_gerekli: false,
    anahtar_kelimeler: ["eller direksiyon beyaz", "hands on wheel standby"],
  },
  {
    id: "trafik-isareti-tanima",
    ad: "Trafik İşareti Tanıma Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page3_img13.png",
    sembol_tanimi: "Kırmızı daireli yasak işareti + sarı daire üzeri çizgi — trafik işareti tanıma",
    kitapcik_aciklama: "Trafik işareti tanıma sistemi uyarı veriyor.",
    anlami: "Trafik işareti tanıma sistemi bir yasak veya hız sınırı tespit etti.",
    nedenler: ["Hız limiti aşıldı", "Yasak manevra algılandı"],
    yapilacaklar: ["Hızı düşür", "Trafik işaretlerine uy"],
    servis_gerekli: false,
    anahtar_kelimeler: ["trafik işareti", "hız sınırı", "sign recognition"],
  },
  {
    id: "trafik-isareti-ariza",
    ad: "Trafik İşareti Tanıma Arızası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page3_img14.png",
    sembol_tanimi: "Kırmızı daireli yasak işareti + kırmızı daire üzeri çizgi — sistem arızası",
    kitapcik_aciklama: "Trafik işareti tanıma sisteminde arıza var.",
    anlami: "Trafik işareti tanıma sistemi arızalı, işaretler algılanamıyor.",
    nedenler: ["Kamera sensörü arızası", "Yazılım hatası", "Sensör kirli"],
    yapilacaklar: [
      "Ön kamera alanını temizle",
      "Aracı yeniden başlat",
      "Devam ederse servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["trafik işareti arıza", "sign recognition arıza"],
  },
];

// ─── Hız Limitleme Sembolleri ─────────────────────────────────────────────────

const HIZ_LIMITLEME_SEMBOLLERI: IkazSembolu[] = [
  {
    id: "hiz-lim-standby",
    ad: "Hız Limitleme Bekleme (Beyaz)",
    renk: "beyaz",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img2.png",
    sembol_tanimi: "Beyaz/gri renkte LIM yazısı + hız kadranı simgesi",
    kitapcik_aciklama: "Hız limitleme sistemi bekleme modunda.",
    anlami: "Hız limitleme sistemi bekleme konumunda — aktif değil.",
    nedenler: ["Sistem açık ama hız limiti ayarlanmamış"],
    yapilacaklar: ["Aktifleştirmek için limitleri ayarla"],
    servis_gerekli: false,
    anahtar_kelimeler: ["LIM standby", "hız limitleme bekleme", "speed limit standby"],
  },
  {
    id: "hiz-lim-aktif",
    ad: "Hız Limitleme Aktif (Sarı)",
    renk: "sari",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img3.png",
    sembol_tanimi: "Sarı renkte LIM yazısı + hız kadranı simgesi",
    kitapcik_aciklama: "Hız limitleme sistemi aktif.",
    anlami: "Hız limitleme sistemi aktif, belirlenen hız üstüne çıkılamaz.",
    nedenler: ["Sürücü hız sınırı belirledi"],
    yapilacaklar: ["Sistemi devre dışı bırakmak için butona bas"],
    servis_gerekli: false,
    anahtar_kelimeler: ["LIM aktif", "hız limitleme aktif", "speed limiter"],
  },
  {
    id: "hiz-lim-aktif-yesil",
    ad: "Hız Limitleme Aktif (Yeşil)",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img25.png",
    sembol_tanimi: "Yeşil renkte LIM yazısı + hız kadranı simgesi",
    kitapcik_aciklama: "Hız limitleme sistemi aktif (yeşil gösterge).",
    anlami: "Hız limitleme sistemi aktif ve hız sınırı dahilinde sürülüyor.",
    nedenler: ["Sürücü hız sınırı belirledi ve limit altında sürüyor"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["LIM yeşil", "hız limitleme aktif yeşil"],
  },
  {
    id: "ilim-standby",
    ad: "Akıllı Hız Limitleme Bekleme (iLIM)",
    renk: "beyaz",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img23.png",
    sembol_tanimi: "Beyaz/gri renkte iLIM yazısı + hız kadranı simgesi",
    kitapcik_aciklama: "Akıllı hız limitleme bekleme modunda.",
    anlami: "Akıllı hız limitleme sistemi (iLIM) bekleme konumunda — trafik işareti tanıma ile çalışır.",
    nedenler: ["Sistem açık ama otomatik limit tespiti bekleniyor"],
    yapilacaklar: ["Normal sürüşe devam et, sistem otomatik algılar"],
    servis_gerekli: false,
    anahtar_kelimeler: ["iLIM standby", "akıllı hız limitleme", "intelligent speed limiter"],
  },
  {
    id: "ilim-aktif",
    ad: "Akıllı Hız Limitleme Aktif (iLIM Yeşil)",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img22.png",
    sembol_tanimi: "Yeşil renkte iLIM yazısı + hız kadranı simgesi",
    kitapcik_aciklama: "Akıllı hız limitleme aktif.",
    anlami: "Akıllı hız limitleme sistemi aktif, yoldaki hız sınırına göre otomatik ayarlıyor.",
    nedenler: ["Trafik işareti algılandı ve limit ayarlandı"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["iLIM aktif", "akıllı hız aktif"],
  },
  {
    id: "ilim-uyari",
    ad: "Akıllı Hız Limitleme Uyarısı (iLIM Sarı)",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page3_img24.png",
    sembol_tanimi: "Sarı renkte iLIM yazısı + hız kadranı simgesi",
    kitapcik_aciklama: "Akıllı hız limitleme uyarısı.",
    anlami: "Akıllı hız limitleme sistemi uyarı veriyor veya hız sınırı aşıldı.",
    nedenler: ["Hız limiti aşıldı", "Sistem sınırı algılayamıyor"],
    yapilacaklar: ["Hızı düşür", "Trafik işaretlerine dikkat et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["iLIM uyarı", "akıllı hız uyarı"],
  },
];

// ─── Far / Aydınlatma Sistem Sembolleri ──────────────────────────────────────

const FAR_SEMBOLLERI: IkazSembolu[] = [
  {
    id: "oto-far-ariza",
    ad: "Otomatik Far Sistemi Arızası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page4_img3.png",
    sembol_tanimi: "Kırmızı renkte far simgesi + A harfi",
    kitapcik_aciklama: "Otomatik far sisteminde arıza var.",
    anlami: "Otomatik far sistemi arızalı, farlar otomatik olarak açılmayabilir.",
    nedenler: ["Far sensörü arızası", "Kamera sistemi hatası"],
    yapilacaklar: [
      "Farları manuel olarak kontrol et",
      "Karanlıkta farları elle aç",
      "Yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["otomatik far arıza", "far sistemi arıza", "auto light arıza"],
  },
  {
    id: "gunduz-farlari",
    ad: "Gündüz Farları (DRL) Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img4.png",
    sembol_tanimi: "Yeşil renkte iki karşılıklı D şekli + yatay çizgiler — gündüz farları",
    kitapcik_aciklama: "Gündüz farları açık.",
    anlami: "Gündüz koşu farları (DRL) aktif.",
    nedenler: ["Araç çalışır durumda, gündüz farları otomatik açık"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["gündüz farları", "DRL", "daytime running lights"],
  },
  {
    id: "oto-far-standby",
    ad: "Otomatik Far Bekleme",
    renk: "beyaz",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img24.png",
    sembol_tanimi: "Beyaz/gri renkte far simgesi + A harfi — otomatik far bekleme",
    kitapcik_aciklama: "Otomatik far sistemi bekleme modunda.",
    anlami: "Otomatik far sistemi açık ama karanlık algılanmadı, farlar kapalı.",
    nedenler: ["Gündüz vakti veya aydınlık ortam"],
    yapilacaklar: ["Normal sürüşe devam et, karardığında otomatik açılır"],
    servis_gerekli: false,
    anahtar_kelimeler: ["otomatik far standby", "auto light bekleme"],
  },
  {
    id: "oto-far-yesil",
    ad: "Otomatik Far Aktif (Yeşil)",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img25.png",
    sembol_tanimi: "Yeşil renkte far simgesi + A harfi — otomatik far aktif",
    kitapcik_aciklama: "Otomatik far sistemi aktif.",
    anlami: "Otomatik far sistemi aktif ve farlar açık durumda.",
    nedenler: ["Karanlık veya loş ortam algılandı"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["otomatik far aktif yeşil", "auto light aktif"],
  },
];

// ─── Park / Çarpışma Sistemi Sembolleri ──────────────────────────────────────

const PARK_CARPISME_SEMBOLLERI: IkazSembolu[] = [
  {
    id: "park-sensor-ariza",
    ad: "Park Sensörü / Çarpışma Sistemi Arızası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page4_img18.png",
    sembol_tanimi: "Kırmızı renkte araç üstten görünüm + etrafında radar/ölçüm dalgaları",
    kitapcik_aciklama: "Park sensörü sisteminde arıza var.",
    anlami: "Park sensörü veya çarpışma önleme sistemi arızalı.",
    nedenler: ["Sensör kirli veya hasarlı", "Sensör kablo bağlantısı sorunu"],
    yapilacaklar: [
      "Sensörlerin üzerini temizle",
      "Yakın mesafe park ederken dikkatli ol",
      "Yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["park sensörü arıza", "geri park arıza", "çarpışma sensör"],
  },
  {
    id: "park-sensor-aktif",
    ad: "Park Sensörü Aktif",
    renk: "sari",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img21.png",
    sembol_tanimi: "Sarı/turuncu renkte araç üstten görünüm + etrafında radar dalgaları",
    kitapcik_aciklama: "Park sensörü aktif, yakın nesne algılandı.",
    anlami: "Park sensörü çalışıyor, yakın çevrede nesne algılandı.",
    nedenler: ["Geri manevra sırasında yakın nesne var"],
    yapilacaklar: ["Yavaş ilerle, etrafı kontrol et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["park sensörü aktif", "geri park uyarısı", "yakın nesne"],
  },
];

// ─── Diğer Eksik Semboller ────────────────────────────────────────────────────

const DIGER_EKSIK_SEMBOLLER: IkazSembolu[] = [
  {
    id: "esp-esc-kirmizi",
    ad: "Elektronik Denge Kontrolü Kritik Arızası (Kırmızı)",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img2.png",
    sembol_tanimi: "Kırmızı renkte kayan araç silüeti — ESC/ESP kritik arıza",
    kitapcik_aciklama: "Elektronik denge kontrol sistemi kritik arızası.",
    anlami: "Elektronik denge kontrol sistemi (ESP/ESC) kritik arızada. Kaygan zeminde araç kontrolü zor olabilir.",
    nedenler: ["ESP kontrol ünitesi arızası", "Tekerlek hız sensörü hatası"],
    yapilacaklar: [
      "Özellikle ıslak/kaygan zeminde dikkatli ol",
      "Hızı düşür",
      "En kısa sürede yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["ESP kırmızı", "ESC kırmızı", "denge arıza kritik"],
  },
  {
    id: "arka-emniyet-kemeri",
    ad: "Arka Yolcu Emniyet Kemeri Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img4.png",
    sembol_tanimi: "Sarı renkte oturan insan figürü + 2 rakamı — arka koltuk emniyet kemeri",
    kitapcik_aciklama: "Arka koltukta emniyet kemeri takılı değil.",
    anlami: "Arka koltuktaki yolcunun emniyet kemeri takılı değil.",
    nedenler: ["Arka yolcu emniyet kemerini takmamış"],
    yapilacaklar: [
      "Arka yolcuya emniyet kemerini taktır",
      "Kemer takılıysa sensör sorununu kontrol et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["arka emniyet kemeri", "yolcu kemeri", "arka koltuk kemer"],
  },
  {
    id: "vites-ariza",
    ad: "Vites / Şanzıman Arızası",
    renk: "kirmizi",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page1_img20.png",
    sembol_tanimi: "Kırmızı renkte P harfi + PRND vites pozisyon göstergesi",
    kitapcik_aciklama: "Şanzıman veya vites sisteminde arıza var.",
    anlami: "Şanzıman veya vites sistemi arızalı. Vites konumu doğru algılanmıyor olabilir.",
    nedenler: ["Şanzıman kontrol ünitesi arızası", "Vites kilidi sensör hatası"],
    yapilacaklar: [
      "Aracı güvenli yerde park et",
      "Motoru kapatıp yeniden başlat",
      "Devam ederse Togg Care'i ara",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["vites arıza", "şanzıman arıza", "PRND arıza"],
  },
  {
    id: "avas",
    ad: "AVAS Yaya Akustik Uyarı Sistemi",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page1_img23.png",
    sembol_tanimi: "Sarı renkte araç yan görünüm + soldan yayılan ses dalgaları simgesi",
    kitapcik_aciklama: "Yaya akustik uyarı sistemi (AVAS) uyarısı.",
    anlami: "Elektrikli araç düşük hızda yayalara ses çıkarmak için AVAS sistemi uyarı veriyor.",
    nedenler: ["AVAS sistemi devre dışı veya arızalı"],
    yapilacaklar: [
      "Yeşil alanlarda yavaş sürüşte yayalara dikkat et",
      "Arıza devam ederse servise git",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["AVAS", "yaya uyarı", "akustik uyarı", "ses sistemi"],
  },
  {
    id: "yuksek-voltaj-sari",
    ad: "Yüksek Voltaj Sistemi Dikkat (Sarı)",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page2_img20.png",
    sembol_tanimi: "Sarı renkte uyarı üçgeni + yıldırım/şimşek işareti",
    kitapcik_aciklama: "Yüksek voltaj sisteminde dikkat gerektiren durum.",
    anlami: "Yüksek voltaj sisteminde uyarı. Kırmızı HV uyarısından daha az acil ama servis gerektiriyor.",
    nedenler: ["HV sistem sensör uyarısı", "Yalıtım direnci düşüklüğü başlangıcı"],
    yapilacaklar: [
      "Normal sürüşe devam edebilirsin",
      "En kısa sürede yetkili servise git",
      "Turuncu bileşenlere dokunmaktan kaçın",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["yüksek voltaj sarı", "HV uyarı sarı", "voltaj dikkat"],
  },
  {
    id: "suruse-hazir-regen",
    ad: "Sürüş Modu / Rejeneratif Fren Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img11.png",
    sembol_tanimi: "Yeşil renkte araç yan görünüm + dişli/çark simgesi",
    kitapcik_aciklama: "Sürüş modu aktif.",
    anlami: "Sürüş modu veya rejeneratif frenleme sistemi aktif.",
    nedenler: ["Sürücü sürüş modunu değiştirdi veya regen frenleme devreye girdi"],
    yapilacaklar: ["Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["sürüş modu", "regen", "rejeneratif fren", "enerji geri kazanım"],
  },
  {
    id: "surucu-uyari-kirmizi",
    ad: "Sürücü Yorgunluk Uyarısı (Kırmızı — Kritik)",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page4_img5.png",
    sembol_tanimi: "Kırmızı renkte göz / bakış simgesi — kritik yorgunluk tespiti",
    kitapcik_aciklama: "Sürücü kritik yorgunluk seviyesinde. Hemen durun.",
    anlami: "Sürücü yorgunluk algılama sistemi kritik seviyede uyarı veriyor. Derhal dur.",
    nedenler: ["Çok uzun sürüş", "Kritik seviyede yorgunluk davranışı tespiti"],
    yapilacaklar: [
      "HEMEN güvenli yerde dur",
      "En az 30 dakika uy veya dinlen",
      "Mümkünse sürücüyü değiştir",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["kırmızı göz", "kritik yorgunluk", "uyku uyarı kırmızı"],
  },
  {
    id: "frene-bas",
    ad: "Frene Bas Hatırlatması",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img17.png",
    sembol_tanimi: "Yeşil renkte ayak simgesi + STOP yazısı",
    kitapcik_aciklama: "Devam etmek için frene basın.",
    anlami: "Aracı hareket ettirmek için fren pedalına basılması gerekiyor.",
    nedenler: ["Vites seçimi veya sürüş başlatmak için fren gerekli"],
    yapilacaklar: ["Fren pedalına bas ve sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["frene bas", "brake to start", "STOP ayak"],
  },
  {
    id: "aksesuar-modu",
    ad: "Aksesuar Modu Aktif",
    renk: "sari",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img12.png",
    sembol_tanimi: "Sarı renkte AKSESUAR yazısı",
    kitapcik_aciklama: "Araç aksesuar modunda.",
    anlami: "Araç aksesuar modunda — motor kapalı ama elektrik sistemleri çalışıyor.",
    nedenler: ["Sürücü aksesuar modunu seçti"],
    yapilacaklar: [
      "Uzun süre bırakma — akü boşalabilir",
      "Sürüş için aracı tam olarak başlat",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["aksesuar modu", "accessory mode", "AKSESUAR"],
  },
];

// ─── Kılavuz Taramasından Eklenen Yeni Semboller ─────────────────────────────

const KILAVUZ_YENI_SEMBOLLER: IkazSembolu[] = [
  // ── Far / Sensör ────────────────────────────────────────────────────────────
  {
    id: "far-yagmur-sensor",
    ad: "Kısa Far — Yağmur/Işık Sensörü Devre Dışı Bıraktı",
    renk: "sari",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page1_img21.png",
    sembol_tanimi: "Sarı renkte kısa far simgesi — yağmur/ışık sensörü tarafından devre dışı bırakıldı",
    kitapcik_aciklama: "Kısa far, yağmur-ışık sensörü tarafından devre dışı bırakıldı.",
    anlami: "Yağmur/ışık sensörü kısa farı otomatik olarak devre dışı bıraktı. Gerekirse farı manuel devreye alın.",
    nedenler: ["Sensör ortam ışığını yeterli buldu", "Sensör arızası"],
    yapilacaklar: ["Far sistemi normal çalışıyorsa sorun yok", "Gerekirse farı manuel aç", "Sorun tekrarlarsa servise git"],
    servis_gerekli: false,
    anahtar_kelimeler: ["yağmur sensörü", "ışık sensörü", "far devre dışı", "sensör far"],
  },
  {
    id: "on-sis-fari",
    ad: "Ön Sis Farı Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img8.png",
    sembol_tanimi: "Yeşil renkte, sola yayılan far ışığı ve üç eğik dalga çizgisi (ön sis)",
    kitapcik_aciklama: "Ön sis farı açık.",
    anlami: "Ön sis farları aktif. Arka sis farından farklı simgedir.",
    nedenler: ["Sürücü ön sis farını açtı"],
    yapilacaklar: ["Sis yokken sis farını kapat", "Sis geçince normal fara dön"],
    servis_gerekli: false,
    anahtar_kelimeler: ["ön sis farı", "front fog light", "sis ön"],
  },

  // ── Güvenlik ────────────────────────────────────────────────────────────────
  {
    id: "cocuk-detektoru-devre-disi",
    ad: "Çocuk Tespit Dedektörü Devre Dışı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img2.png",
    sembol_tanimi: "Sarı renkte bebek/çocuk simgesi — devre dışı bırakılmış göstergesiyle",
    kitapcik_aciklama: "Çocuk tespit dedektörü devre dışı bırakıldı.",
    anlami: "Araçtaki çocuk/bebek algılama sistemi devre dışı. Araçtan ayrılırken çocukların içeride olmadığını kendiniz kontrol edin.",
    nedenler: ["Sistem manuel devre dışı bırakıldı", "Sistem arızası"],
    yapilacaklar: [
      "Araçtan ayrılmadan önce çocukların içeride kalmadığını kontrol et",
      "Sistemi yeniden etkinleştirmeyi dene",
      "Sorun devam ederse servise git",
    ],
    servis_gerekli: false,
    not: "Sıcak havada araçta çocuk bırakmak hayati tehlike oluşturur.",
    anahtar_kelimeler: ["çocuk dedektörü", "bebek algılama", "çocuk tespit devre dışı"],
  },
  {
    id: "kapi-acik-uyari",
    ad: "Kapı / Kaput / Bagaj / Şarj Kapağı Açık Uyarısı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page5_img2.jpeg",
    sembol_tanimi: "Araç üstten görünümü — açık kapı/kaput/bagaj/şarj kapağı vurgulu olarak gösterilir",
    kitapcik_aciklama: "Bir kapı, kaput, bagaj kapağı veya şarj kapağı tam kapalı değil.",
    anlami: "Araç hareket halindeyken bir kapı, kaput, bagaj veya şarj kapağı açık ya da tam kilitlenmemiş. Simge kaybolana kadar ilgili kapıları sıkıca kapatın.",
    nedenler: [
      "Kapı tam kapanmamış",
      "Kaput mandalı tutmamış",
      "Bagaj kapağı açık",
      "Şarj kapağı kapatılmamış",
    ],
    yapilacaklar: [
      "Güvenli bir yerde dur",
      "Hangi kapının açık olduğunu ekrandan kontrol et",
      "İlgili kapıyı sıkıca kapat",
      "Uyarı kaybolmazsa kilidi kontrol et",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["kapı açık", "kaput açık", "bagaj açık", "şarj kapağı açık", "kapı uyarısı"],
  },

  // ── Kör Nokta ───────────────────────────────────────────────────────────────
  {
    id: "kor-nokta-sag",
    ad: "Kör Nokta Uyarısı — Sağ Şerit",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img5.png",
    sembol_tanimi: "Sarı renkte araç yan görünümü, sağ tarafta radar/uyarı dalgası",
    kitapcik_aciklama: "Kör nokta izleme sistemi sağ şeritte araç algıladı.",
    anlami: "Sağ kör noktada araç var. Sağa şerit değiştirmeden önce dikkat edin.",
    nedenler: ["Sağ şeritte araç var"],
    yapilacaklar: ["Sağ aynadan ve direkt bakışla kontrol et", "Sinyal ver ve güvenli olduğundan emin ol"],
    servis_gerekli: false,
    anahtar_kelimeler: ["kör nokta sağ", "blind spot sağ", "sağ şerit uyarı"],
  },

  // ── Hız Sabitleyici ─────────────────────────────────────────────────────────
  {
    id: "onerilenhiz-onayla",
    ad: "Önerilen Hız Sınırını Onayla",
    renk: "sari",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page2_img9.png",
    sembol_tanimi: "Sarı renkte hız sınırı tabelası + onay/ret seçeneği göstergesi",
    kitapcik_aciklama: "Önerilen hız sınırını kabul edin veya reddedin.",
    anlami: "Akıllı hız limitleme (iLIM) sistemi bir hız sınırı tespit etti ve sürücünün onayını bekliyor.",
    nedenler: ["iLIM sistemi trafik işareti tespit etti"],
    yapilacaklar: [
      "Direksiyon düğmesiyle onayla veya reddet",
      "Kabul edersen araç otomatik hız sınırını uygular",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["hız sınırı onayla", "iLIM onay", "hız kabul", "speed limit accept"],
  },
  {
    id: "hiz-sabitleyici-standby",
    ad: "Hız Sabitleyici Bekleme",
    renk: "beyaz",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page2_img11.png",
    sembol_tanimi: "Beyaz/gri renkte hız sabitleyici simgesi — bekleme durumunda",
    kitapcik_aciklama: "Hız sabitleyici beklemede.",
    anlami: "Standart hız sabitleyici (cruise control) sistemi açık ama henüz hız ayarlanmamış.",
    nedenler: ["Sistem etkinleştirildi, hız bekleniyor"],
    yapilacaklar: ["Hız ayarlamak için direksiyondaki butonu kullan"],
    servis_gerekli: false,
    anahtar_kelimeler: ["hız sabitleyici standby", "cruise control bekleme", "CC beyaz"],
  },
  {
    id: "hiz-sabitleyici-ariza",
    ad: "Hız Sabitleyici Arızası",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page2_img13.png",
    sembol_tanimi: "Sarı renkte hız sabitleyici simgesi + ünlem/çarpı arıza göstergesi",
    kitapcik_aciklama: "Hız sabitleyici sisteminde arıza var.",
    anlami: "Hız sabitleyici (cruise control) sistemi arızalı, kullanılamaz.",
    nedenler: ["Cruise control kontrol ünitesi hatası", "Sensör arızası"],
    yapilacaklar: [
      "Aracı kapatıp yeniden başlat",
      "Devam ederse yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["hız sabitleyici arıza", "cruise control arıza", "CC arıza"],
  },
  {
    id: "acc-gecersiz",
    ad: "Adaptif Hız Sabitleyici — Geçersiz Kılındı",
    renk: "sari",
    aciliyet: "dikkat",
    model: "hepsi",
    gorsel: "page2_img14.jpeg",
    sembol_tanimi: "Sarı renkte ACC simgesi — geçersiz kılındı/override durumu (yanıp söner: geçersiz, sabit: aktif)",
    kitapcik_aciklama: "Adaptif hız sabitleyici aktif fakat geçersiz kılındı veya aktif.",
    anlami: "Adaptif hız sabitleyici sürücü müdahalesi ile geçici olarak geçersiz kılındı ya da aktif çalışıyor.",
    nedenler: ["Sürücü gaz/fren pedalına bastı", "Sistem aktif ama override modu"],
    yapilacaklar: ["Sistemi yeniden etkinleştirmek için düğmeye bas", "Normal sürüşe devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["ACC override", "adaptif hız geçersiz", "cruise override"],
  },

  // ── Şerit Güvenlik Asistanı ─────────────────────────────────────────────────
  {
    id: "serit-guvenlik-pasif",
    ad: "Şerit Güvenlik Asistanı Pasif",
    renk: "beyaz",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img5.jpeg",
    sembol_tanimi: "Beyaz/gri renkte şerit çizgileri arasında araç — pasif/bekleme durumu",
    kitapcik_aciklama: "Şerit güvenlik asistanı pasif durumda.",
    anlami: "Şerit güvenlik asistanı açık ama pasif konumda — şeritler algılanamıyor veya hız düşük.",
    nedenler: ["Hız çok düşük (genellikle <60 km/s)", "Şerit çizgisi yok veya soluk"],
    yapilacaklar: ["Normal sürüşe devam et", "Uygun hız ve şerit koşullarında otomatik aktifleşir"],
    servis_gerekli: false,
    anahtar_kelimeler: ["şerit asistanı pasif", "lane assist pasif", "LSA pasif"],
  },
  {
    id: "serit-guvenlik-devre-disi",
    ad: "Şerit Güvenlik Asistanı Devre Dışı",
    renk: "sari",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img8.png",
    sembol_tanimi: "Sarı renkte şerit çizgileri arasında araç — devre dışı veya kontrolde göstergesiyle (sabit=devre dışı, yanıp söner=kontrolde)",
    kitapcik_aciklama: "Şerit güvenlik asistanı devre dışı veya aktif kontrolde.",
    anlami: "Sabit yanıyorsa sistem devre dışı bırakılmış. Yanıp sönüyorsa sistem aktif müdahale ediyor.",
    nedenler: ["Sürücü tarafından kapatıldı", "Şerit güvenlik sistemi aktif müdahale ediyor"],
    yapilacaklar: ["Yeniden etkinleştirmek için düğmeye bas", "Yanıp sönüyorsa direksiyonu kontrol et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["şerit güvenlik devre dışı", "LSA kapalı", "lane safety off"],
  },
  {
    id: "serit-acil-takip-devre-disi",
    ad: "Acil Durum Şerit Takibi Devre Dışı",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page3_img9.png",
    sembol_tanimi: "Sarı renkte acil durum şerit takip sistemi devre dışı + şeritten ayrılma uyarısı bekleme",
    kitapcik_aciklama: "Acil durum şerit takibi devre dışı ve şeritten ayrılma uyarısı bekleme durumunda.",
    anlami: "Acil durum şerit takip sistemi devre dışı, şeritten ayrılma uyarısı da bekleme konumunda.",
    nedenler: ["Sistem arızası", "Sensör görüşü engellenmiş"],
    yapilacaklar: ["Aracı yeniden başlat", "Devam ederse yetkili servise git"],
    servis_gerekli: true,
    anahtar_kelimeler: ["acil şerit takip", "ELK devre dışı", "emergency lane keeping off"],
  },

  // ── ADAS Yanal/Uzunsal Durum Kombinasyonları ─────────────────────────────────
  {
    id: "adas-yanal-ariza-uzunsal-aktif",
    ad: "Sürücü Asistanı — Yanal Kontrol Arıza / Uzunsal Kontrol Aktif",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page3_img12.png",
    sembol_tanimi: "Sarı renkte adaptif sürücü asistanı simgesi — yanal kontrol arıza, ileri/geri kontrol aktif",
    kitapcik_aciklama: "Adaptif sürücü asistanı yanal kontrolü arıza, ileri/geri kontroller aktif.",
    anlami: "Sürücü destek sisteminin şerit takibi (yanal) arızalı ancak hız kontrolü (uzunsal) çalışıyor.",
    nedenler: ["Kamera veya yanal kontrol ünitesi arızası"],
    yapilacaklar: ["Şerit takibini manuel kontrol et", "Yetkili servise git"],
    servis_gerekli: true,
    anahtar_kelimeler: ["ADAS yanal arıza", "sürücü asistanı yanal arıza", "lateral control fault"],
  },
  {
    id: "adas-yanal-ariza-uzunsal-pasif",
    ad: "Sürücü Asistanı — Yanal Kontrol Arıza / Uzunsal Kontrol Pasif",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page3_img19.png",
    sembol_tanimi: "Sarı renkte adaptif sürücü asistanı simgesi — yanal kontrol arıza, ileri/geri kontrol pasif",
    kitapcik_aciklama: "Adaptif sürücü asistanı yanal kontrolü arıza, ileri/geri kontrol pasif.",
    anlami: "Hem şerit takibi (yanal) arızalı hem de hız kontrolü (uzunsal) pasif durumda.",
    nedenler: ["Birden fazla ADAS sensörü arızası"],
    yapilacaklar: ["Yetkili servise git"],
    servis_gerekli: true,
    anahtar_kelimeler: ["ADAS çift arıza", "sürücü asistanı arıza"],
  },
  {
    id: "adas-yanal-pasif-uzunsal-aktif",
    ad: "Sürücü Asistanı — Yanal Kontrol Pasif / Uzunsal Kontrol Aktif",
    renk: "sari",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page3_img20.png",
    sembol_tanimi: "Sarı renkte adaptif sürücü asistanı simgesi — yanal kontrol pasif, ileri/geri kontrol aktif",
    kitapcik_aciklama: "Adaptif sürücü asistanı yanal kontrolü pasif, ileri/geri kontrolü aktif.",
    anlami: "Şerit takibi pasif konumda, hız/mesafe kontrolü aktif çalışıyor.",
    nedenler: ["Şeritler algılanamıyor", "Yanal kontrol manuel kapatılmış"],
    yapilacaklar: ["Normal sürüşe devam et", "Şerit takibi otomatik devreye girer"],
    servis_gerekli: false,
    anahtar_kelimeler: ["ADAS yanal pasif", "ACC aktif şerit pasif"],
  },
  {
    id: "adas-yanal-pasif-uzunsal-hata",
    ad: "Sürücü Asistanı — Yanal Kontrol Pasif / Uzunsal Kontrol Hata",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page3_img21.png",
    sembol_tanimi: "Sarı renkte adaptif sürücü asistanı simgesi — yanal kontrol pasif, ileri/geri kontrol hata",
    kitapcik_aciklama: "Adaptif sürücü asistanı yanal kontrolü pasif, ileri/geri kontrolü hata durumunda.",
    anlami: "Şerit takibi pasif, hız/mesafe kontrolünde hata var.",
    nedenler: ["Radar veya hız sensörü arızası"],
    yapilacaklar: ["Aracı yeniden başlat", "Devam ederse yetkili servise git"],
    servis_gerekli: true,
    anahtar_kelimeler: ["ADAS uzunsal hata", "ACC arıza yanal pasif"],
  },

  // ── Yokuş / Çapraz Trafik / Tek Pedal ───────────────────────────────────────
  {
    id: "yokus-inis-ariza",
    ad: "Yokuş İniş Kontrolü Arızası",
    renk: "sari",
    aciliyet: "yakin_servis",
    model: "hepsi",
    gorsel: "page4_img13.png",
    sembol_tanimi: "Sarı renkte eğimli zeminde inen araç simgesi + arıza göstergesi",
    kitapcik_aciklama: "Yokuş iniş kontrolü sisteminde arıza var.",
    anlami: "Yokuş iniş kontrolü (HDC) sistemi arızalı. Dik inişlerde manuel fren gerekebilir.",
    nedenler: ["HDC sistem sensörü arızası", "Fren sistemi hatası"],
    yapilacaklar: [
      "Dik inişlerde daha düşük hız ve daha fazla fren mesafesi kullan",
      "Yetkili servise git",
    ],
    servis_gerekli: true,
    anahtar_kelimeler: ["yokuş iniş arıza", "HDC arıza", "hill descent arıza"],
  },
  {
    id: "capraz-trafik-sol",
    ad: "Çapraz Trafik Uyarısı / Otomatik Fren — Sol",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page4_img14.jpeg",
    sembol_tanimi: "Kırmızı renkte araç + soldan gelen çapraz trafik uyarısı, otomatik frenleme göstergesi",
    kitapcik_aciklama: "Çapraz trafik uyarısı — sol taraftan araç geliyor, otomatik fren devreye girebilir.",
    anlami: "Geri manevra sırasında sol taraftan yaklaşan araç tespit edildi. Sistem otomatik fren uygulayabilir.",
    nedenler: ["Park çıkışında sol taraftan araç geliyor"],
    yapilacaklar: ["HEMEN dur", "Sol tarafı kontrol et", "Güvenli olduğunda devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["çapraz trafik sol", "RCTA sol", "geri park uyarı sol"],
  },
  {
    id: "capraz-trafik-sag",
    ad: "Çapraz Trafik Uyarısı / Otomatik Fren — Sağ",
    renk: "kirmizi",
    aciliyet: "hemen_dur",
    model: "hepsi",
    gorsel: "page4_img15.jpeg",
    sembol_tanimi: "Kırmızı renkte araç + sağdan gelen çapraz trafik uyarısı, otomatik frenleme göstergesi",
    kitapcik_aciklama: "Çapraz trafik uyarısı — sağ taraftan araç geliyor, otomatik fren devreye girebilir.",
    anlami: "Geri manevra sırasında sağ taraftan yaklaşan araç tespit edildi. Sistem otomatik fren uygulayabilir.",
    nedenler: ["Park çıkışında sağ taraftan araç geliyor"],
    yapilacaklar: ["HEMEN dur", "Sağ tarafı kontrol et", "Güvenli olduğunda devam et"],
    servis_gerekli: false,
    anahtar_kelimeler: ["çapraz trafik sağ", "RCTA sağ", "geri park uyarı sağ"],
  },
  {
    id: "tek-pedal-aktif",
    ad: "Tek Pedalla Duraklatmalı Sürüş Aktif",
    renk: "yesil",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img16.png",
    sembol_tanimi: "Yeşil renkte tek pedal / rejeneratif frenleme aktif simgesi",
    kitapcik_aciklama: "Tek pedalla duraklatmalı sürüş fonksiyonu aktif.",
    anlami: "Tek pedal modu aktif. Gaz pedalını bırakınca araç rejeneratif frenle tamamen durana kadar yavaşlar.",
    nedenler: ["Sürücü tek pedal modunu etkinleştirdi"],
    yapilacaklar: [
      "Gaz pedalını bırakınca araç yavaşlar ve durur",
      "Fren pedalı hâlâ kullanılabilir",
      "Devre dışı bırakmak için düğmeye bas",
    ],
    servis_gerekli: false,
    anahtar_kelimeler: ["tek pedal", "one pedal driving", "tek pedal sürüş", "duraklatmalı sürüş"],
  },
  {
    id: "bekleme-modu",
    ad: "Bekleme Modu Açık",
    renk: "sari",
    aciliyet: "bilgi",
    model: "hepsi",
    gorsel: "page4_img20.jpeg",
    sembol_tanimi: "Sarı renkte bekleme/standby modu simgesi",
    kitapcik_aciklama: "Bekleme modu açık.",
    anlami: "Araç bekleme modunda. Sistem düşük güç tüketiminde hazır durumda.",
    nedenler: ["Sürücü bekleme modunu etkinleştirdi veya araç otomatik geçti"],
    yapilacaklar: ["Normal sürüşe devam etmek için aracı tam başlat"],
    servis_gerekli: false,
    anahtar_kelimeler: ["bekleme modu", "standby modu", "sleep mode"],
  },
];

// ─── Tüm semboller birleşik liste ─────────────────────────────────────────────

export const TUM_IKAZ_SEMBOLLERI: IkazSembolu[] = [
  ...KIRMIZI_IKAZLAR,
  ...SARI_UYARILAR,
  ...BILGI_LAMBALARI,
  ...T10F_OZGUL,
  ...ILAVE_KIRMIZI_IKAZLAR,
  ...ILAVE_SARI_UYARILAR,
  ...ILAVE_BILGI_LAMBALARI,
  ...KAPLUMBAGA_SEMBOLLERI,
  ...ADAS_SEMBOLLERI,
  ...HIZ_LIMITLEME_SEMBOLLERI,
  ...FAR_SEMBOLLERI,
  ...PARK_CARPISME_SEMBOLLERI,
  ...DIGER_EKSIK_SEMBOLLER,
  ...KILAVUZ_YENI_SEMBOLLER,
];

// Görsel eşleştirme için Claude'a gönderilecek özet liste
export const SEMBOL_OZET_LISTESI = TUM_IKAZ_SEMBOLLERI.map((s) => ({
  id: s.id,
  ad: s.ad,
  renk: s.renk,
  sembol_tanimi: s.sembol_tanimi,
}));

export const ACILIYET_ETIKETLER: Record<AciliyetDuzeyi, string> = {
  hemen_dur: "Hemen Dur!",
  yakin_servis: "Yakın Servise Git",
  dikkat: "Dikkat Et",
  bilgi: "Bilgi",
};

export const RENK_SINIF: Record<IkazRengi, { bg: string; text: string; border: string; badge: string }> = {
  kirmizi: {
    bg: "bg-red-50 dark:bg-red-950/20",
    text: "text-red-600 dark:text-red-400",
    border: "border-red-200 dark:border-red-800",
    badge: "bg-red-100 text-red-700 dark:bg-red-900/50 dark:text-red-300",
  },
  sari: {
    bg: "bg-amber-50 dark:bg-amber-950/20",
    text: "text-amber-600 dark:text-amber-400",
    border: "border-amber-200 dark:border-amber-800",
    badge: "bg-amber-100 text-amber-700 dark:bg-amber-900/50 dark:text-amber-300",
  },
  yesil: {
    bg: "bg-green-50 dark:bg-green-950/20",
    text: "text-green-600 dark:text-green-400",
    border: "border-green-200 dark:border-green-800",
    badge: "bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300",
  },
  mavi: {
    bg: "bg-blue-50 dark:bg-blue-950/20",
    text: "text-blue-600 dark:text-blue-400",
    border: "border-blue-200 dark:border-blue-800",
    badge: "bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300",
  },
  beyaz: {
    bg: "bg-neutral-50 dark:bg-neutral-900",
    text: "text-neutral-600 dark:text-neutral-400",
    border: "border-neutral-200 dark:border-neutral-700",
    badge: "bg-neutral-100 text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300",
  },
};

export const ACILIYET_RENK: Record<AciliyetDuzeyi, string> = {
  hemen_dur: "bg-red-600 text-white",
  yakin_servis: "bg-orange-500 text-white",
  dikkat: "bg-amber-400 text-amber-900",
  bilgi: "bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300",
};
